---
title: "Homework"
tbl-colwidths: [20, 5, 5, 10]
---

This page contains information about and a schedule of the homework assignments for the semester.

## General Information

-  While the instructions for each assignment are available through the linked pages for quick and public access, **if you are in the class you must use the link provided in [Ed Discussion](http://us.edstem.org) to accept the assignment**. This will ensure that:
    - You have compatible versions of all relevant packages provided in the environment;
    - You have a GitHub repository that you can use to share your code.
- Submit assignments by 9:00pm Eastern Time on the due date on [Gradescope](https://gradescope.com).
- Starting with HW2, groups of at most two students can submit group solutions. Groups do not have the be the same for all assignments. **Exactly one member of each group should submit the solution**. If you submit as a group, **it is the responsibility of the submitter to tell Gradescope the names of the other group members**. If this information is not entered, the other group members' grades can be delayed or even lost. Also include the names and NetIDs of all group members on the first page.
- If a student in BEE 5750 works in a group with a student from BEE 4750, they should submit separate PDFs to Gradescope (these can be different versions of the same PDF) due to the additional 5750 problem; this will just not be graded for the 4750 student(s). A single submission can be used for multiple students within the same course number who share a group.
- More detailed [homework instructions and logistics](../policies/homework.qmd#homework-logistics) are available.
- Submissions must be PDFs. Make sure that you tag the pages corresponding to each question; points will be deducted otherwise.
- To convert the assignment notebook to PDF, you can use VS Code to render the notebook to HTML, and then use your browser to print to PDF. If you have set up LaTeX with VS Code, you can convert directly to a PDF. 
- As an alternative, when you commit and push a `.ipynb` file (a Jupyter Notebook) to your repository, we have set up a [GitHub Action](https://docs.github.com/en/actions) to automatically render your notebook to a PDF, which you can then download and submit to Gradescope. However, sometimes GitHub actions can take a while or can stall out, so you'll need to monitor this and give yourself some time. If you've waited a while and your notebook isn't rendering, reach out on Ed and we can figure out what's going on. In the worst case (you push your changes close to the deadline), the timestamp of your commit will be evidence that you completed the assignment on time, even if we can't render the PDF until the next day.

## Grading

Make sure to look over the [standard homework rubric](../policies/rubric.qmd) and familiarize yourself with the [homework](../policies/homework.qmd) and [grading policies](../policies/grading.qmd).

## Schedule

| Assignment | Instructions | Solutions | Due Date |
|:----------:|:------------:|:---------:|:--------:|
| Homework 1 | [{{< fa sharp pen-field >}}](hw01/hw01.qmd) | [{{< fa sharp key-skeleton >}}](../solutions/hw01/hw01.qmd) | Sep. 11, 2025 |
| Homework 2 | [{{< fa sharp pen-field >}}](hw02/hw02.qmd) | [{{< fa sharp key-skeleton >}}](../solutions/hw02/hw02.qmd) | Sep. 25, 2025 |
| Homework 3 | [{{< fa sharp pen-field >}}](hw03/hw03.qmd) | [{{< fa sharp key-skeleton >}}](../solutions/hw03/hw03.qmd) | Oct. 23, 2025 |
| Homework 4 | [{{< fa sharp pen-field >}}](hw04/hw04.qmd) | | Nov. 06, 2025 |
| Homework 5 | | | Dec. 04, 2025 |
