---
title: "BEE 4750 Lab 3: Linear Programming with JuMP"
date: last-modified
format:
    html:        
        warning: true
        error: true
    ipynb:
        warning: true
        error: true
        code-annotation: below
    pdf:
        include-in-header: 
           text: |
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
execute: 
    echo: true
engine: julia
julia:
    exeflags: ["+1.11.5"]
format-links: [pdf, ipynb]
---

::: {.content-visible when-format="ipynb"}
**Name**:

**ID**:
:::

::: {.callout-important icon="false"}
### Due Date

Thursday, 10/23/24, 9:00pm
:::

::: {.content-visible when-format="html"}
::: callout-caution
If you are enrolled in the course, make sure that you use the GitHub Classroom link provided in Ed Discussion, or you may not be able to get help if you run into problems.

Otherwise, you can [find the Github repository here]({{< var github_org.repo >}}/lab03).
:::
:::

## Setup

The following code should go at the top of most Julia scripts; it will load the local package environment and install any needed packages. You will see this often and shouldn't need to touch it.

```{julia}
#| output: false

import Pkg
Pkg.activate(".")
Pkg.instantiate()
```

```{julia}
#| output: false

using JuMP # optimization modeling syntax
using HiGHS # optimization solver
```


## Overview

In this lab, you will write and solve a resource allocation example using `JuMP.jl`. `JuMP.jl` provides an intuitive syntax for writing, solving, and querying optimization problems.

`JuMP` requires the loading of a solver. [Each supported solver works for certain classes of problems, and some are open source while others require a commercial license]. We will use the `HiGHS` solver, which is open source and works for linear, mixed integer linear, and quadratic programs.

In this lab we will walk through the steps involved in coding a linear program in HiGHS, solving it, and querying the solution.

## Exercise (3 points)

Your task is to decide how much lumber to produce to maximize profit from wood sales. You can purchase wood from a managed forest, which consists of spruce (320,000 bf) and fir (720,000 bf). Spruce costs $\$0.12$ per bf to purchase and fir costs $\$0.08$ per bf.

At the lumber mill, wood can be turned into plywood of various grades (see @tbl-inputs for how much wood of each type is required for and the revenue from each grade). Any excess wood is sent to be recycled into particle board, which yields no revenue for the mill. 


| Plywood Grade | Inputs (bf/bf plywood) | Revenue (\$/1000 bf) |
|:-------------:|:----------------------:|:--------------------:|
|       1       |   0.5 (S) + 1.5 (F)    |         400          |
|       2       |   1.0 (S) + 2.0 (F)    |         520          |
|       3       |   1.5 (S) + 2.0 (F)    |         700          |

: Wood inputs and revenue by plywood grade. S refers to spruce inputs, F fir inputs. {#tbl-inputs}



First, we need to identify our decision variables. While there are several options, we will use $G_i$, the amount of each grade the mill produces (in 1000 bf). 

Using these decision variables, formulate a linear program to maximize the profit of the mill subject to the supply constraints on spruce and fir.

::: {.callout-tip}
## JuMP Syntax

The core pieces of setting up a `JuMP` model involve specifying the model and adding variables, the objective, and constraints. At the most simple level, this syntax looks like this:

```julia
m = Model(HiGHS.Optimizer)
@variable(m, lb <= x <= ub) # if you do not have upper or lower bounds, you can drop those accordingly
@variable(m, lb <= y <= ub)
@objective(m, Max, 100x + 250y) # replace Max with Min depending on the problem
@constraint(m, label, 6x + 12y <= 80) # replace "label" with some meaningful string you would like to use later to query shadow prices, or drop it
```

You can add more constraints or more variables as needed.

:::


::: {.callout-tip}
## Using Array Syntax

You can set up multiple variables or constraints at once using array syntax. For example, the following are equivalent:

```julia
@variable(m, G1 >= 0)
@variable(m, G2 >= 0)
@variable(m, G3 >= 0)
```

and

```julia
@variable(m, G[1:3] >= 0)
```

You can also set up multiple constraints using arrays of coefficients and/or bounds. For example:

```julia
I = 1:3
d = [0; 3; 5]
@constraint(m, demand[i in I], G[i] >= d[i])
```
:::

`JuMP` is finicky about changing objects and constraints, so I recommend setting up all of the model syntax in one notebook cell, which is what we will do here. 

```{julia}
forest_model = Model(HiGHS.Optimizer) # initialize model object
@variable(forest_model, G[1:3] >= 0) # non-negativity constraints
# uncomment the following lines and add the objective and constraints as needed for the model
# @objective(forest_model, )
# @constraint(forest_model, )
print(forest_model) # this outputs a nicely formatted summary of the model so you can check your specification
```

Next, to optimize, use the `optimize!()` function:

```{julia}
optimize!(forest_model)
```

You should get confirmation that a solution was found; if one was not, there's a chance something was wrong with your model formulation.

To find the values of the decision variables, use `value()` (which can be broadcasted over variable arrays):

```{julia}
@show value.(G);
```

Similarly, `objective_value()` finds the optimal value of the objective:

```{julia}
@show objective_value(forest_model);
```

Finally, we can find the dual values of the constraints with `shadow_price()`. Do this for the constraints in your model using the block below.
```{julia}
# @show shadow_price(name_of_constraint);
```

`JuMP` also lets you evaluate other expressions that you might be interested in based on the solutions. For example, you can use the following block to calculate the total amount of plywood the mill would produce under the optimal solution:

```{julia}
@expression(forest_model, total_plywood, sum(G))
@show value.(total_plywood);
```


## References

Put any consulted sources here, including classmates you worked with/who helped you.