---
title: "Labs"
tbl-colwidths: [20, 5, 5, 10]
format: 
    html: default
---

This page contains information about and a schedule of the lab assignments for the semester.

## General Information

- You can download each lab notebook through the link below.
- Submit assignments by 9:00pm Eastern Time on the due date on [Gradescope](https://gradescope.com).
- Submissions must be PDFs. Make sure that you tag the pages corresponding to each question; points will be deducted otherwise.
- To convert the assignment notebook to PDF, you can use VS Code to render the notebook to HTML, and then use your browser to print to PDF. If you have set up LaTeX with VS Code, you can convert directly to a PDF.

## Grading

Labs are graded on a scale of 0-2 on the basis of effort towards demonstrated work, rather than absolute correctness or completion (see the [syllabus](../syllabus.qmd)). No labs are dropped by default. Lab worksheets are due by 9:00pm on the day after the lab.

## Schedule

| Lab | Instructions | Solutions | Due Date | 
|:----------:|:------:|:------:|:------------:|
| Lab 1: Discretization and Convergence (Sep. 21) | [{{< fa sharp pen-field >}}](lab01/lab01.qmd) |  [{{< fa sharp key-skeleton  >}}](../solutions/lab01/lab01.qmd) | Sep. 21, 2026 |
| Lab 2: Linear Programming with JuMP (Oct. 26) | {{< fa sharp pen-field >}} | {{< fa sharp key-skeleton >}} | Oct. 27, 2026 |
| Lab 3: Fixed Costs and Facility Siting (Nov. 11) | {{< fa sharp pen-field >}} | {{< fa sharp key-skeleton >}} | Nov. 12, 2026 |
| Lab 4: Scenario Trees and Sequential Decisions (Nov. 23) | {{< fa sharp pen-field >}} | {{< fa sharp key-skeleton >}} | Nov. 24, 2026 |

Instructions and solutions are linked as each lab is released.
