<!DOCTYPE html>
<html lang="en"><head>
<link href="../_assets/logos/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e44360b8a8db1e130c7792fece1c8032.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.3">

  <meta name="author" content="Vivek Srikrishnan">
  <meta name="dcterms.date" content="2026-11-09">
  <title>Environmental Systems Analysis – Solid Waste and Network Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-d52ba59528acaf0ac8c09f3308d87e37.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <!-- MathJax 3 -->
  <script>
  window.MathJax = {
      tex: {
        tags: 'ams'
      }
    };
  </script>
  <!-- Mathjax 3 config -->
  <script>
  window.MathJax = {
      {
        minScale: 0.5
        loader: {load: ['[tex]/tagformat']},
        tex: {packages: {'[+]': ['tagformat']}}
      }
    };
    MathJax = {
    options: {
      menuOptions: {
        settings: {
          assistiveMml: false,   // true to enable assitive MathML
          collapsible: false,   // true to enable collapsible math
          explorer: false      // true to enable the expression explorer
        }
      }
    }
  };
  </script>
<meta property="og:title" content="Solid Waste and Network Models – Environmental Systems Analysis">
<meta property="og:description" content="Lecture 18">
<meta property="og:site_name" content="Environmental Systems Analysis">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="center">
    <h1 class="title">Solid Waste and Network Models</h1>
  <hr>
<p class="subtitle">Lecture 18</p>
<p class="date">November 9, 2026</p>
</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Overview</h2>
<ul>
<li><a href="#/review-of-last-class" id="/toc-review-of-last-class">Review of Last Class</a></li>
<li><a href="#/solid-waste-management" id="/toc-solid-waste-management">Solid Waste Management</a></li>
<li><a href="#/waste-management-example" id="/toc-waste-management-example">Waste Management Example</a></li>
<li><a href="#/solving-it" id="/toc-solving-it">Solving It</a></li>
<li><a href="#/key-takeaways" id="/toc-key-takeaways">Key Takeaways</a></li>
<li><a href="#/upcoming-schedule" id="/toc-upcoming-schedule">Upcoming Schedule</a></li>
<li><a href="#/appendix" id="/toc-appendix">Appendix</a></li>
</ul>
</nav>
</section>
<section>
<section id="review-of-last-class" class="title-slide slide level1 center">
<h1>Review of Last Class</h1>

</section>
<section id="binaries-switch-facilities-on-and-off" class="slide level2">
<h2>Binaries Switch Facilities On and Off</h2>
<p>An optional facility needs a <strong>binary</strong> <span class="math inline">\(u \in \{0, 1\}\)</span>:</p>
<ul>
<li>fixed cost <span class="math inline">\(\times\, u\)</span> in the objective (paid only if it operates);</li>
<li>output <span class="math inline">\(\leq\)</span> capacity <span class="math inline">\(\times\, u\)</span> (a closed facility does nothing).</li>
</ul>
<p>Today: the same idea when the decisions are <strong>flows</strong> through a network.</p>
<aside class="notes">
<p>SUB SHEET (one page; read this before class).</p>
<p>Today’s four takeaways: (1) In a network model the decisions are the flows along the arcs, and the constraints are conservation at each node: what arrives equals what leaves, transformed (a recycler passes on 60% as residual, a combustor leaves 20% as ash). (2) A facility that might not operate needs a binary. It appears twice: fixed cost times Y in the objective, and in the capacity constraint, flow in at most capacity times Y, so a closed facility takes nothing. (3) Facilities can open for non-obvious reasons: here the waste-to-energy plant runs only because the landfill is full. Make the landfill 20 Mg/day larger and it closes. (4) The network alone is not a model: you also need what happens at each node, costs, and the rules.</p>
<p>Key numbers (all computed in the deck): optimal cost about $26,881 per day with all three facilities open; with a 220 Mg/day landfill the WTE closes and the cost drops to about $24,539 per day.</p>
<p>Likely questions. Why is the WTE open if it is expensive? Because the landfill is exactly full, and the recycler’s residual has to go somewhere. Why is the binary in the capacity constraint? So that a closed facility cannot receive anything: one constraint does the job of “if Y is zero, no flow”. What is “residual”? What a facility passes on after processing: the recycler sends 60% of what it receives onward, and the combustor leaves 20% as ash.</p>
<p>Logistics: HW9 is assigned today and is due Thursday, November 19 (network models and waste allocation). Quiz 5 is Monday, November 16. The TA runs this week’s lab (Lab 3, facility siting in JuMP). Every question on a slide has its answer as the next fragment, so no board work is needed. If the poll does not work on your account, skip it.</p>
<p>Timing: be on “Solid Waste Management” by minute 4, the example system by minute 22, the costs by minute 28, the mass balances by minute 38, solving by minute 52, and the takeaways by minute 64. If short, cut in this order: the discussion on the what-if slide (show the table only), the transfer-station check, the “Network Models Elsewhere” slide, the worked cost coefficient.</p>
<p>On this slide: one minute. Recall from the mixed integer programming lecture that a binary variable turns an on/off decision into linear constraints. Today that idea meets a network.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="questions" class="slide level2">
<h2>Questions?</h2>
<div class="columns center">
<div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/vsrikrish-poll.png" class="quarto-figure quarto-figure-center" style="width:100.0%" alt="Poll Everywhere QR Code"></p>
</figure>
</div>
</div><div class="column" style="width:60%;">
<p><strong>Text</strong>: VSRIKRISH to 22333</p>
<p><strong>URL</strong>: <a href="https://pollev.com/vsrikrish">https://pollev.com/vsrikrish</a> <br><br> <a href="https://www.polleverywhere.com/multiple_choice_polls/qKeig0hHShZYHAOmvZtZm?preview=true&amp;controls=none" data-preview-link="true">See Results</a></p>
</div></div>
<aside class="notes">
<p>Take a question or two about last week, about two minutes. If the poll link does not work for you, ask for hands instead.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="solid-waste-management" class="title-slide slide level1 center">
<h1>Solid Waste Management</h1>

</section>
<section id="waste-load-allocation" class="slide level2">
<h2>Waste Load Allocation</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Some relevant questions:</p>
<ul>
<li>Where do we send waste?</li>
<li>What types of facilities do we build/operate?</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="https://www.epa.gov/sites/default/files/styles/medium/public/2015-08/hierarchy_hierarchy_and_options_pages.png" style="width:100.0%"></p>
<figcaption>Waste Management Hierarchy</figcaption>
</figure>
</div>
<div class="caption">
<p>Source: <a href="https://www.epa.gov/homeland-security-waste/waste-management-options-homeland-security-incidents">EPA</a></p>
</div>
</div></div>
<aside class="notes">
<p>About three minutes. A city produces waste every day and has to put it somewhere. The options form a hierarchy: reduce first, then recycle, then recover energy, and landfill last. Two kinds of decision are tangled together: where each truckload goes (a routing decision that can vary continuously), and which facilities to build or keep open (an on/off decision). That combination is why this is a mixed integer problem.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="waste-allocation-as-a-network" class="slide level2">
<h2>Waste Allocation As A Network</h2>
<p>Want to model <em>flows</em> between waste sources and sinks (disposal sites).</p>

<img data-src="figures/waste-network-blank.svg" style="width:75.0%" class="r-stretch quarto-figure-center"><p class="caption">Network Representation</p><aside class="notes">
<p>About two minutes. A network has nodes (cities, facilities) and arcs (the roads between them). The decisions are how much flows along each arc. Point out that some arcs go from one facility to another: what a facility does not fully dispose of has to be shipped on.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="network-parameterization" class="slide level2">
<h2>Network Parameterization</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/waste-network-params.svg"></p>
<figcaption>Network Parameterization</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color{purple}S_i\)</span></td>
<td style="text-align: left;">Waste produced at source <span class="math inline">\(i\)</span> (Mg/day)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\color{red}K_j\)</span></td>
<td style="text-align: left;">Capacity of disposal <span class="math inline">\(j\)</span> (Mg/day)</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\color{blue}W_{ij}\)</span></td>
<td style="text-align: left;">Waste transported from source <span class="math inline">\(i\)</span> to disposal <span class="math inline">\(j\)</span> (Mg/day)</td>
</tr>
</tbody>
</table>
</div></div>
<aside class="notes">
<p>About two minutes. Three symbols to carry through the lecture: S for what each source produces, K for what each facility can take, and W for the flow on each arc. W is the decision. Mg is a megagram, a metric ton.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="conservation-at-each-node" class="slide level2">
<h2>Conservation at Each Node</h2>
<p>At every node, flow is <strong>conserved</strong>: a source ships everything it produces, <span class="math inline">\(\sum_j W_{ij} = S_i\)</span>, and a facility passes on a fixed fraction of what arrives.</p>
<p><strong>Check</strong>: A transfer station receives 40 Mg/day from each of two cities and sends it all to a landfill (<span class="math inline">\(T_L\)</span>) or a recycler (<span class="math inline">\(T_R\)</span>). Write its constraint.</p>
<div class="fragment fade-in">
<p><span class="math display">\[T_L + T_R = 40 + 40 = 80 \text{ Mg/day}\]</span></p>
</div>
<aside class="notes">
<p>About four minutes. Conservation is the core of every network model: nothing is created or destroyed at a node, only routed or transformed. Give the class a minute on the transfer station, then reveal the answer: what leaves equals what arrives. A facility is the same idea with a transformation: a recycler that recovers 40% passes on the other 60%. If short on time, skip the check and reveal the answer directly.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-is-missing" class="slide level2">
<h2>What Is Missing?</h2>
<p>The network captures the graph structure of the system, but nothing else. <strong>What else might we need?</strong></p>
<div class="fragment fade-in">
<ul>
<li>System dynamics (fate &amp; transport)</li>
<li>Objectives</li>
<li>Costs</li>
<li>Management goals and/or regulatory constraints</li>
</ul>
</div>
<aside class="notes">
<p>About two minutes. Ask the question and take a couple of answers before revealing the list. The graph says what is connected to what; it says nothing about what a recycler or an incinerator does to the waste, what anything costs, or what the rules are. All of that has to come from outside the network.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="waste-management-example" class="title-slide slide level1 center">
<h1>Waste Management Example</h1>

</section>
<section id="example-system" class="slide level2">
<h2>Example System</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/waste-example-network.svg"></p>
<figcaption>Waste Management Example</figcaption>
</figure>
</div>
</div><div class="column" style="width:40%;">
<p>Three disposal options:</p>
<ul>
<li>Waste-to-Energy (WTE)</li>
<li>Materials Recovery Facility (MRF)</li>
<li>Landfill (LF)</li>
</ul>
</div></div>
<aside class="notes">
<p>About two minutes (you should be here by about minute 22). Two cities, producing 100 and 170 Mg/day, and three facilities with the capacities in red. Distances in blue. Note the arcs between facilities: the recycler (MRF) sends its residual to the incinerator (WTE) or the landfill, and the incinerator sends its ash to the landfill.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="decision-variables" class="slide level2">
<h2>Decision Variables</h2>
<p><strong><em>What are our decision variables?</em></strong></p>
<div class="fragment fade-in">
<table class="caption-top">
<colgroup>
<col style="width: 40%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(W_{ij}\)</span></td>
<td style="text-align: left;">Waste transported from city <span class="math inline">\(i\)</span> to disposal <span class="math inline">\(j\)</span> (Mg/day)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(R_{kj}\)</span></td>
<td style="text-align: left;">Residual waste transported from disposal <span class="math inline">\(k\)</span> to disposal <span class="math inline">\(j\)</span> (Mg/day)</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(Y_j\)</span></td>
<td style="text-align: left;">Operational status (on/off) of disposal <span class="math inline">\(j\)</span> (binary)</td>
</tr>
</tbody>
</table>
</div>
<aside class="notes">
<p>About three minutes. Ask, wait, then reveal. Three kinds: flows from cities (W), flows of residuals between facilities (R), and whether each facility operates (Y, binary). The residual flows here are R21 (MRF to WTE), R23 (MRF to landfill), and R13 (WTE ash to landfill). The facility numbering is WTE 1, MRF 2, landfill 3.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-does-it-cost" class="slide level2">
<h2>What Does It Cost?</h2>
<ul>
<li><strong>Transportation</strong>: <span class="math inline">\(\sum_{i, j} a_{ij} \, l_{ij} \, W_{ij}\)</span> ($/Mg-km × km × Mg/day), plus residuals.</li>
<li><strong>Disposal</strong>: a fixed cost <span class="math inline">\(c_j\)</span> ($/day) and a tipping cost <span class="math inline">\(b_j\)</span> ($/Mg).</li>
</ul>
<div class="fragment fade-in">
<p><span class="math display">\[\text{Disposal cost} = \sum_j \left[c_j + b_j \times (\text{everything arriving at } j)\right]\]</span></p>
<p><strong>Is this right?</strong></p>
</div>
<aside class="notes">
<p>About three minutes. Build the two cost components. Then ask whether the disposal expression is right, and give the class a moment. The problem is the fixed cost: as written, every facility pays it even if it receives nothing. The next slide fixes that.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fixed-costs-need-an-onoff-variable" class="slide level2">
<h2>Fixed Costs Need an On/Off Variable</h2>
<p>The fixed cost is paid <strong>only if the facility operates</strong>:</p>
<p><span class="math display">\[Y_j = \begin{cases}0 &amp; \text{if facility } j \text{ is not operated} \\ 1 &amp; \text{if facility } j \text{ is operated} \end{cases}\]</span></p>
<div class="fragment fade-in">
<p><span class="math display">\[\text{Disposal cost} = \sum_j \left[c_j \, Y_j + b_j \times (\text{everything arriving at } j)\right]\]</span></p>
</div>
<aside class="notes">
<p>About two minutes. This is the fixed-cost pattern from the mixed integer lecture: fixed cost times the binary. On its own it is not enough, because nothing yet stops waste from being sent to a facility with Y equal to zero. The capacity constraint will close that gap.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-examples-costs" class="slide level2">
<h2>The Example’s Costs</h2>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Facility</th>
<th style="text-align: right;">Fixed cost ($/yr)</th>
<th style="text-align: right;">Fixed cost ($/day)</th>
<th style="text-align: right;">Tipping ($/Mg)</th>
<th style="text-align: right;">Capacity (Mg/day)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">WTE</td>
<td style="text-align: right;">900,000</td>
<td style="text-align: right;">2,466</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">150</td>
</tr>
<tr class="even">
<td style="text-align: left;">MRF</td>
<td style="text-align: right;">400,000</td>
<td style="text-align: right;">1,096</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">130</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LF</td>
<td style="text-align: right;">700,000</td>
<td style="text-align: right;">1,918</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">200</td>
</tr>
</tbody>
</table>
<p>Transport costs $1.5/Mg-km. The MRF recycles 40% of what it receives, at $35/Mg recycled, and passes on the rest; the WTE leaves 20% of its input as ash.</p>
<aside class="notes">
<p>About two minutes. The daily fixed costs are the annual costs divided by 365. The recycler is cheap to run but only handles waste: what it does not recycle (60%) still has to go to the incinerator or the landfill.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="working-out-one-cost-coefficient" class="slide level2">
<h2>Working Out One Cost Coefficient</h2>
<div class="columns">
<div class="column" style="width:48%;">
<p>Sending 1 Mg from City 1 to the MRF (5 km) costs</p>
<p><span class="math display">\[\underbrace{1.5 \times 5}_{\text{haul}} + \underbrace{5}_{\text{tip}} + \underbrace{0.4 \times 35}_{\text{recycle}}\]</span></p>
<p>= <strong>$26.5/Mg</strong>.</p>
</div><div class="column" style="width:52%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">$/Mg</th>
<th style="text-align: right;">WTE</th>
<th style="text-align: right;">MRF</th>
<th style="text-align: right;">LF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">City 1</td>
<td style="text-align: right;">82.5</td>
<td style="text-align: right;">26.5</td>
<td style="text-align: right;">85</td>
</tr>
<tr class="even">
<td style="text-align: left;">City 2</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">41.5</td>
<td style="text-align: right;">77.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MRF residual</td>
<td style="text-align: right;">82.5</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">88</td>
</tr>
<tr class="even">
<td style="text-align: left;">WTE ash</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">67</td>
</tr>
</tbody>
</table>
</div></div>
<aside class="notes">
<p>About three minutes. Work one coefficient aloud: haul 5 km at 1.50 a Mg-km, tip 5 dollars, and recycle 40% of the ton at 35 dollars per ton recycled. Every other entry is built the same way; for example City 1 to the WTE is 1.5 times 15 plus 60, which is 82.5. The residual rows include the tipping cost at the facility receiving them. If short on time, skip the worked line and show only the table.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mass-balance-for-cities-and-residuals" class="slide level2">
<h2>Mass Balance for Cities and Residuals</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p><strong>Cities</strong> ship everything they produce:</p>
<p><span class="math inline">\(W_{11} + W_{12} + W_{13} =\)</span> 100</p>
<p><span class="math inline">\(W_{21} + W_{22} + W_{23} =\)</span> 170</p>
</div><div class="column" style="width:55%;">
<div class="fragment fade-in">
<p><strong>Residuals</strong> (fate and transport):</p>
<p>WTE ash: <span class="math display">\[R_{13} = 0.2\,(W_{11} + W_{21} + R_{21})\]</span></p>
<p>MRF residual: <span class="math display">\[R_{21} + R_{23} = 0.6\,(W_{12} + W_{22})\]</span></p>
</div>
</div></div>
<aside class="notes">
<p>About four minutes (you should be here by about minute 38). These are conservation constraints. The city ones say every ton goes somewhere. The residual ones carry the facility physics: the incinerator turns everything it burns, including residual sent from the recycler, into 20% ash that must be landfilled; the recycler passes on 60% of what it receives.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="linking-capacity-to-onoff" class="slide level2">
<h2>Linking Capacity to On/Off</h2>
<p>Everything <strong>arriving</strong> counts; a closed facility takes <strong>nothing</strong>:</p>
<p><span class="math display">\[
\begin{aligned}
\text{WTE:}&amp; \quad W_{11} + W_{21} + R_{21} \leq 150\,Y_1 \\
\text{MRF:}&amp; \quad W_{12} + W_{22} \leq 130\,Y_2 \\
\text{LF:}&amp; \quad W_{13} + W_{23} + R_{13} + R_{23} \leq 200\,Y_3
\end{aligned}
\]</span></p>
<p><strong>Check</strong>: Which constraints need a binary, and why?</p>
<div class="fragment fade-in">
<p>Only the capacity constraints, because <span class="math inline">\(Y_j = 0\)</span> has to stop anything arriving.</p>
</div>
<aside class="notes">
<p>About four minutes. This one constraint per facility does two jobs: it is the capacity limit when the facility is open, and it forces every incoming flow to zero when it is closed. That is why Y belongs here and not in the city balances. Make sure the landfill line includes the residual and ash arriving from the other facilities: everything that arrives counts.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-full-problem" class="slide level2">
<h2>The Full Problem</h2>
<p><span class="math display">\[
\begin{aligned}
\min_{W, R, Y} \quad &amp; \sum_{i, j} C_{ij} W_{ij} + \sum_{k, j} C^R_{kj} R_{kj} + \sum_j c_j Y_j \\
\text{subject to:} \quad &amp; \textstyle\sum_j W_{ij} = S_i \\
&amp; \text{residual out of } k = \text{fraction} \times \text{input to } k \\
&amp; \textstyle\sum_i W_{ij} + \sum_k R_{kj} \leq K_j\,Y_j \\
&amp; W_{ij},\, R_{kj} \geq 0, \quad Y_j \in \{0, 1\}
\end{aligned}
\]</span></p>
<p>The constraints cover the cities, fate and transport, capacity linked to on/off, and signs.</p>
<aside class="notes">
<p>About two minutes. The same problem in general form, which is what HW9 asks for on a different network. It is a mixed integer linear program: linear in everything, with three binary variables.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="solving-it" class="title-slide slide level1 center">
<h1>Solving It</h1>

</section>
<section id="solving-the-example-in-jump" class="slide level2">
<h2>Solving the Example in JuMP</h2>
<div id="14" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a></a><span class="kw">function</span> <span class="fu">solve_waste</span>(; landfill_capacity<span class="op">=</span>capacity[<span class="fl">3</span>])</span>
<span id="cb1-2"><a></a>    cap <span class="op">=</span> [capacity[<span class="fl">1</span>], capacity[<span class="fl">2</span>], landfill_capacity]</span>
<span id="cb1-3"><a></a>    model <span class="op">=</span> <span class="fu">Model</span>(HiGHS.Optimizer)</span>
<span id="cb1-4"><a></a>    <span class="fu">set_silent</span>(model)</span>
<span id="cb1-5"><a></a>    <span class="pp">@variable</span>(model, W[<span class="fl">1</span><span class="op">:</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">3</span>] <span class="op">&gt;=</span> <span class="fl">0</span>)        <span class="co"># city i -&gt; facility j [Mg/day]</span></span>
<span id="cb1-6"><a></a>    <span class="pp">@variable</span>(model, R21 <span class="op">&gt;=</span> <span class="fl">0</span>)                <span class="co"># MRF residual -&gt; WTE</span></span>
<span id="cb1-7"><a></a>    <span class="pp">@variable</span>(model, R23 <span class="op">&gt;=</span> <span class="fl">0</span>)                <span class="co"># MRF residual -&gt; LF</span></span>
<span id="cb1-8"><a></a>    <span class="pp">@variable</span>(model, R13 <span class="op">&gt;=</span> <span class="fl">0</span>)                <span class="co"># WTE ash -&gt; LF</span></span>
<span id="cb1-9"><a></a>    <span class="pp">@variable</span>(model, Y[<span class="fl">1</span><span class="op">:</span><span class="fl">3</span>], Bin)             <span class="co"># facility operates?</span></span>
<span id="cb1-10"><a></a>    <span class="pp">@objective</span>(model, Min, <span class="fu">sum</span>(city_cost[i, j] <span class="op">*</span> W[i, j] <span class="cf">for</span> i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">2</span>, j <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">3</span>) <span class="op">+</span></span>
<span id="cb1-11"><a></a>        cost_R21 <span class="op">*</span> R21 <span class="op">+</span> cost_R23 <span class="op">*</span> R23 <span class="op">+</span> cost_R13 <span class="op">*</span> R13 <span class="op">+</span> <span class="fu">sum</span>(fixed_cost[j] <span class="op">*</span> Y[j] <span class="cf">for</span> j <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">3</span>))</span>
<span id="cb1-12"><a></a>    <span class="pp">@constraint</span>(model, city[i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">2</span>], <span class="fu">sum</span>(W[i, <span class="op">:</span>]) <span class="op">==</span> waste[i])</span>
<span id="cb1-13"><a></a>    <span class="pp">@constraint</span>(model, ash, R13 <span class="op">==</span> ash_rate <span class="op">*</span> (W[<span class="fl">1</span>, <span class="fl">1</span>] <span class="op">+</span> W[<span class="fl">2</span>, <span class="fl">1</span>] <span class="op">+</span> R21))</span>
<span id="cb1-14"><a></a>    <span class="pp">@constraint</span>(model, residual, R21 <span class="op">+</span> R23 <span class="op">==</span> (<span class="fl">1</span> <span class="op">-</span> recycle_rate) <span class="op">*</span> (W[<span class="fl">1</span>, <span class="fl">2</span>] <span class="op">+</span> W[<span class="fl">2</span>, <span class="fl">2</span>]))</span>
<span id="cb1-15"><a></a>    <span class="pp">@constraint</span>(model, wte, W[<span class="fl">1</span>, <span class="fl">1</span>] <span class="op">+</span> W[<span class="fl">2</span>, <span class="fl">1</span>] <span class="op">+</span> R21 <span class="op">&lt;=</span> cap[<span class="fl">1</span>] <span class="op">*</span> Y[<span class="fl">1</span>])</span>
<span id="cb1-16"><a></a>    <span class="pp">@constraint</span>(model, mrf, W[<span class="fl">1</span>, <span class="fl">2</span>] <span class="op">+</span> W[<span class="fl">2</span>, <span class="fl">2</span>] <span class="op">&lt;=</span> cap[<span class="fl">2</span>] <span class="op">*</span> Y[<span class="fl">2</span>])</span>
<span id="cb1-17"><a></a>    <span class="pp">@constraint</span>(model, lf, W[<span class="fl">1</span>, <span class="fl">3</span>] <span class="op">+</span> W[<span class="fl">2</span>, <span class="fl">3</span>] <span class="op">+</span> R13 <span class="op">+</span> R23 <span class="op">&lt;=</span> cap[<span class="fl">3</span>] <span class="op">*</span> Y[<span class="fl">3</span>])</span>
<span id="cb1-18"><a></a>    <span class="fu">optimize!</span>(model)</span>
<span id="cb1-19"><a></a>    <span class="cf">return</span> (cost<span class="op">=</span><span class="fu">objective_value</span>(model), W<span class="op">=</span><span class="fu">value</span>.(W), R21<span class="op">=</span><span class="fu">value</span>(R21), R23<span class="op">=</span><span class="fu">value</span>(R23),</span>
<span id="cb1-20"><a></a>        R13<span class="op">=</span><span class="fu">value</span>(R13), Y<span class="op">=</span><span class="fu">round</span>.(<span class="dt">Int</span>, <span class="fu">value</span>.(Y)),</span>
<span id="cb1-21"><a></a>        lf_load<span class="op">=</span><span class="fu">value</span>(W[<span class="fl">1</span>, <span class="fl">3</span>] <span class="op">+</span> W[<span class="fl">2</span>, <span class="fl">3</span>] <span class="op">+</span> R13 <span class="op">+</span> R23), cap<span class="op">=</span>cap)</span>
<span id="cb1-22"><a></a><span class="cf">end</span></span>
<span id="cb1-23"><a></a></span>
<span id="cb1-24"><a></a>base <span class="op">=</span> <span class="fu">solve_waste</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The optimal cost is <strong>$26,881/day</strong>, and all 3 facilities operate.</p>
<aside class="notes">
<p>About three minutes. You do not need to walk through the code line by line: open the fold to show that every constraint on the previous slides appears once, with the binaries declared as Bin and the capacity constraints multiplied by Y. The point is that the formulation goes into JuMP almost word for word. HW9 uses a different network, so this is a pattern to adapt, not an answer to copy.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-solution" class="slide level2">
<h2>The Solution</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/waste-example-solution.svg"></p>
<figcaption>Waste Management Problem Solution</figcaption>
</figure>
</div>
</div><div class="column" style="width:45%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Flow</th>
<th style="text-align: right;">Mg/day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">City 1 → MRF</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">City 2 → LF</td>
<td style="text-align: right;">170</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MRF residual → WTE</td>
<td style="text-align: right;">37.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">MRF residual → LF</td>
<td style="text-align: right;">22.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WTE ash → LF</td>
<td style="text-align: right;">7.5</td>
</tr>
</tbody>
</table>
</div></div>
<aside class="notes">
<p>About two minutes. Read the flows off the figure. City 1 sends everything to the nearby recycler. City 2 sends everything to the landfill. The recycler’s residual is split between the incinerator and the landfill, and the incinerator’s ash goes to the landfill too.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-is-the-wte-open" class="slide level2">
<h2>Why Is the WTE Open?</h2>
<p>The WTE costs $2,466/day just to open. <strong>Why pay that to burn 37.5 Mg/day?</strong></p>
<div class="fragment fade-in">
<p>Because the <strong>landfill is full</strong>: it takes 200 of its 200 Mg/day. The recycler’s residual has to go somewhere, and the only other place is the WTE.</p>
<p>The WTE operates because of a binding constraint somewhere else in the network, not because it is cheap.</p>
</div>
<aside class="notes">
<p>About three minutes. Give the class a minute to look at the flows before revealing. This is the network lesson: decisions at one node are driven by limits at another. The next slide tests that explanation by changing the landfill.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-if-the-landfill-were-bigger" class="slide level2">
<h2>What If the Landfill Were Bigger?</h2>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb2-1"><a></a>bigger <span class="op">=</span> <span class="fu">solve_waste</span>(landfill_capacity<span class="op">=</span><span class="fl">220</span>)</span>
<span id="cb2-2"><a></a><span class="fu">println</span>(<span class="st">"| Landfill capacity (Mg/day) | Cost (</span><span class="sc">\\</span><span class="st">\$/day) | WTE | MRF | LF |"</span>)</span>
<span id="cb2-3"><a></a><span class="fu">println</span>(<span class="st">"|:--|--:|:--:|:--:|:--:|"</span>)</span>
<span id="cb2-4"><a></a><span class="cf">for</span> r <span class="kw">in</span> (base, bigger)</span>
<span id="cb2-5"><a></a>    status <span class="op">=</span> <span class="fu">fill</span>(<span class="st">"open"</span>, <span class="fl">3</span>)</span>
<span id="cb2-6"><a></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">3</span></span>
<span id="cb2-7"><a></a>        <span class="cf">if</span> r.Y[j] <span class="op">==</span> <span class="fl">0</span></span>
<span id="cb2-8"><a></a>            status[j] <span class="op">=</span> <span class="st">"**closed**"</span></span>
<span id="cb2-9"><a></a>        <span class="cf">end</span></span>
<span id="cb2-10"><a></a>    <span class="cf">end</span></span>
<span id="cb2-11"><a></a>    <span class="fu">println</span>(<span class="st">"| "</span>, r.cap[<span class="fl">3</span>], <span class="st">" | "</span>, <span class="fu">commas</span>(r.cost), <span class="st">" | "</span>, <span class="fu">join</span>(status, <span class="st">" | "</span>), <span class="st">" |"</span>)</span>
<span id="cb2-12"><a></a><span class="cf">end</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Landfill capacity (Mg/day)</th>
<th style="text-align: right;">Cost ($/day)</th>
<th style="text-align: center;">WTE</th>
<th style="text-align: center;">MRF</th>
<th style="text-align: center;">LF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">200</td>
<td style="text-align: right;">26,881</td>
<td style="text-align: center;">open</td>
<td style="text-align: center;">open</td>
<td style="text-align: center;">open</td>
</tr>
<tr class="even">
<td style="text-align: left;">220</td>
<td style="text-align: right;">24,539</td>
<td style="text-align: center;"><strong>closed</strong></td>
<td style="text-align: center;">open</td>
<td style="text-align: center;">open</td>
</tr>
</tbody>
</table>
<p>With 20 Mg/day more landfill, the <strong>WTE closes</strong> and the system saves $2,342/day. City 2 now sends 25 Mg/day to the MRF, and all 75 Mg/day of the MRF’s residual goes to the landfill.</p>
<aside class="notes">
<p>About three minutes (you should be on the takeaways by about minute 64). This confirms the explanation on the previous slide: as soon as the landfill has room for the recycler’s residual, the incinerator is no longer worth its fixed cost, so the binary switches it off. This is what “interpret which facilities open” means on HW9: say which constraint makes each facility worth opening. If short on time, show the table and skip the discussion.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="key-takeaways" class="title-slide slide level1 center">
<h1>Key Takeaways</h1>

</section>
<section id="key-takeaways-1" class="slide level2">
<h2>Key Takeaways</h2>
<ul>
<li>A network model’s decisions are <strong>flows</strong> on arcs, constrained by <strong>conservation</strong> at each node.</li>
<li>An optional facility needs a <strong>binary</strong>: fixed cost <span class="math inline">\(\times\, Y_j\)</span> in the objective, and flow in <span class="math inline">\(\leq K_j Y_j\)</span>.</li>
<li>Facilities can open for <strong>non-obvious reasons</strong>: the WTE runs only because the landfill is full.</li>
<li>A network graph becomes a model only with fate and transport, costs, and rules.</li>
</ul>
<aside class="notes">
<p>About two minutes. Read the four takeaways. The third is the one to dwell on: in a network, the reason a facility operates is often a constraint somewhere else.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="network-models-elsewhere" class="slide level2">
<h2>Network Models Elsewhere</h2>
<ul>
<li>Can have more advanced network models with highly-specified routes
<ul>
<li>Transportation networks</li>
<li>Power transmission networks</li>
<li>Pipeline networks</li>
</ul></li>
<li>Can also add flow constraints rather than just mass-balance.</li>
<li>Flows could also be bidirectional.</li>
</ul>
<aside class="notes">
<p>About one minute, or skip if short. The same structure (flows on arcs, conservation at nodes, capacities, sometimes on/off decisions) covers transportation, power transmission, and pipelines. Power flow adds physics that determines how flow splits across lines, rather than letting the planner choose freely.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="upcoming-schedule" class="title-slide slide level1 center">
<h1>Upcoming Schedule</h1>

</section>
<section id="next-classes" class="slide level2">
<h2>Next Classes</h2>
<p><strong>This week</strong>: Lab 3, Fixed Costs and Facility Siting in JuMP, with the TA (bring a laptop).</p>
<p><strong>Monday, November 16</strong>: Quiz 5, then stochastic optimization and scenario trees.</p>
<aside class="notes">
<p>About one minute. Do not say which day the lab is on: depending on scheduling it may come before or after this lecture.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="assessments" class="slide level2">
<h2>Assessments</h2>
<p><strong>HW9</strong>: assigned today, due Thursday, November 19 (network models and waste allocation).</p>
<p><strong>Project update</strong>: due Friday, November 13.</p>
<p><strong>Quiz 5</strong>: Monday, November 16 (capacity expansion, mixed integer programming, and waste and network models).</p>
<aside class="notes">
<p>About one minute. Remind students that HW9 asks them to set up a different, small network themselves.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="appendix" class="title-slide slide level1 center">
<h1>Appendix</h1>

</section>
<section id="indicator-constraints-in-jump" class="slide level2">
<h2>Indicator Constraints in JuMP</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource julia number-lines code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a></a><span class="pp">@variable</span>(waste, Y[<span class="fl">1</span><span class="op">:</span><span class="fl">3</span>], Bin)</span>
<span id="cb3-2"><a></a><span class="pp">@constraint</span>(waste, commit_mrf, !Y[<span class="fl">2</span>] <span class="op">=&gt;</span> {W[<span class="fl">1</span>, <span class="fl">2</span>] <span class="op">+</span> W[<span class="fl">2</span>, <span class="fl">2</span>] <span class="op">==</span> <span class="fl">0</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Some solvers let you write the on/off logic directly. This says: if <span class="math inline">\(Y_2 = 0\)</span>, nothing arrives at the MRF, <span class="math inline">\(W_{12} + W_{22} = 0\)</span>. For the WTE, the arriving flow also includes the MRF residual: <span class="math inline">\(W_{11} + W_{21} + R_{21} = 0\)</span> when <span class="math inline">\(Y_1 = 0\)</span>.</p>
<p>The capacity-linking constraint used in the lecture does the same job and works with every solver.</p>
<aside class="notes">
<p>Reference only. Indicator constraints are a convenience some solvers support. The linking constraint, arriving flow at most capacity times Y, is the portable way to write the same logic.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="big-m-reformulation" class="slide level2">
<h2>Big-M Reformulation</h2>
<p>Not every solver supports indicator constraints. The general trick is a <strong>big-M</strong> constraint:</p>
<p><span class="math display">\[M\,Y_2 \geq W_{12} + W_{22}, \qquad M\,Y_1 \geq W_{11} + W_{21} + R_{21}\]</span></p>
<p>where <span class="math inline">\(M\)</span> is larger than any feasible value of the right-hand side.</p>
<p>Choosing <span class="math inline">\(M = K_j\)</span> (the facility’s capacity) gives exactly the capacity-linking constraint from the lecture.</p>
<aside class="notes">
<p>Reference only. A smaller valid M gives a tighter LP relaxation, which helps branch and bound; the capacity is the natural choice here because no feasible flow can exceed it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"numbers":true},
'chalkboard': {"buttons":true,"theme":"whiteboard"},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: false,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/envsys\.viveks\.me\/fall2025");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
                // target, if specified
                link.setAttribute("target", "_blank");
                if (link.getAttribute("rel") === null) {
                  link.setAttribute("rel", "noopener");
                }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>