{
  "hash": "8999f5eb928cbbf0dea5bff003e0f448",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"Homework 4 Solutions\"\ndate: last-modified\nformat:\n    html:        \n        warning: true\n        error: true\n    ipynb:\n        warning: true\n        error: true\n        code-annotation: below\n    pdf:\n        include-in-header: \n           text: |\n            \\usepackage{fvextra}\n            \\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\\\\{\\}}\n            \\DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\\\\{\\}}\nengine: julia\njulia:\n    exeflags: [\"+1.11.5\"]\nformat-links: [pdf, ipynb]\n---\n\n::: {.content-visible when-format=\"ipynb\"}\n**Name**:\n\n**ID**:\n:::\n\n::: {.callout-important icon=false}\n### Due Date\n\nThursday, 11/06/25, 9:00pm\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n:::{.callout-caution}\n\nIf you are enrolled in the course, make sure that you use the GitHub Classroom link provided in Ed Discussion, or you may not be able to get help if you run into problems.\n\nOtherwise, you can [find the Github repository here]({{< var github_org.repo >}}/hw04).\n\n:::\n\n:::\n\n## Overview\n\n\n### Load Environment\n\nThe following code loads the environment and makes sure all needed packages are installed. This should be at the start of most Julia scripts.\n\n::: {#2 .cell execution_count=1}\n``` {.julia .cell-code}\nimport Pkg\nPkg.activate(@__DIR__)\nPkg.instantiate()\n```\n:::\n\n\n\n::: {#4 .cell execution_count=1}\n``` {.julia .cell-code}\nusing JuMP\nusing HiGHS\nusing DataFrames\nusing Plots\nusing Measures\nusing CSV\nusing MarkdownTables\nusing LaTeXStrings\n```\n:::\n\n\n\n## Problems (Total: 30 Points)\n\n### Problem 1 (Total: 3 Points)\n\nWe know that an optimal solution has to occur at the intersection of constraints. It's helpful (though not necessary) to plot the feasible domain to find the locations of these points, which we do in @fig-p1-domain.\n\n::: {#cell-fig-p1-domain .cell execution_count=1}\n\n::: {#fig-p1-domain .cell-output .cell-output-display execution_count=1}\n```{=html}\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"672\" height=\"480\" viewBox=\"0 0 2688 1920\">\n<defs>\n  <clipPath id=\"clip860\">\n    <rect x=\"0\" y=\"0\" width=\"2688\" height=\"1920\"/>\n  </clipPath>\n</defs>\n<path clip-path=\"url(#clip860)\" d=\"M0 1920 L2688 1920 L2688 -4.26326e-14 L0 -4.26326e-14  Z\" fill=\"#ffffff\" fill-rule=\"evenodd\" fill-opacity=\"1\"/>\n<defs>\n  <clipPath id=\"clip861\">\n    <rect x=\"537\" y=\"0\" width=\"1883\" height=\"1883\"/>\n  </clipPath>\n</defs>\n<path clip-path=\"url(#clip860)\" d=\"M115.057 1734.12 L2640.76 1734.12 L2640.76 47.2441 L115.057 47.2441  Z\" fill=\"#ffffff\" fill-rule=\"evenodd\" fill-opacity=\"1\"/>\n<defs>\n  <clipPath id=\"clip862\">\n    <rect x=\"115\" y=\"47\" width=\"2527\" height=\"1688\"/>\n  </clipPath>\n</defs>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"437.353,1734.12 437.353,47.2441 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"938.982,1734.12 938.982,47.2441 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"1440.61,1734.12 1440.61,47.2441 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"1942.24,1734.12 1942.24,47.2441 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"2443.87,1734.12 2443.87,47.2441 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"115.057,1378.36 2640.76,1378.36 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"115.057,967.683 2640.76,967.683 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"115.057,557.002 2640.76,557.002 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:2; stroke-opacity:0.1; fill:none\" points=\"115.057,146.321 2640.76,146.321 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"115.057,1734.12 2640.76,1734.12 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"437.353,1734.12 437.353,1715.22 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"938.982,1734.12 938.982,1715.22 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"1440.61,1734.12 1440.61,1715.22 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"1942.24,1734.12 1942.24,1715.22 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"2443.87,1734.12 2443.87,1715.22 \"/>\n<path clip-path=\"url(#clip860)\" d=\"M437.353 1767.34 Q433.742 1767.34 431.914 1770.9 Q430.108 1774.45 430.108 1781.58 Q430.108 1788.68 431.914 1792.25 Q433.742 1795.79 437.353 1795.79 Q440.988 1795.79 442.793 1792.25 Q444.622 1788.68 444.622 1781.58 Q444.622 1774.45 442.793 1770.9 Q440.988 1767.34 437.353 1767.34 M437.353 1763.64 Q443.164 1763.64 446.219 1768.24 Q449.298 1772.83 449.298 1781.58 Q449.298 1790.3 446.219 1794.91 Q443.164 1799.49 437.353 1799.49 Q431.543 1799.49 428.465 1794.91 Q425.409 1790.3 425.409 1781.58 Q425.409 1772.83 428.465 1768.24 Q431.543 1763.64 437.353 1763.64 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip860)\" d=\"M929.364 1794.89 L937.003 1794.89 L937.003 1768.52 L928.692 1770.19 L928.692 1765.93 L936.956 1764.26 L941.632 1764.26 L941.632 1794.89 L949.271 1794.89 L949.271 1798.82 L929.364 1798.82 L929.364 1794.89 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip860)\" d=\"M1435.26 1794.89 L1451.58 1794.89 L1451.58 1798.82 L1429.64 1798.82 L1429.64 1794.89 Q1432.3 1792.13 1436.88 1787.5 Q1441.49 1782.85 1442.67 1781.51 Q1444.92 1778.98 1445.8 1777.25 Q1446.7 1775.49 1446.7 1773.8 Q1446.7 1771.04 1444.75 1769.31 Q1442.83 1767.57 1439.73 1767.57 Q1437.53 1767.57 1435.08 1768.34 Q1432.65 1769.1 1429.87 1770.65 L1429.87 1765.93 Q1432.69 1764.79 1435.15 1764.21 Q1437.6 1763.64 1439.64 1763.64 Q1445.01 1763.64 1448.2 1766.32 Q1451.4 1769.01 1451.4 1773.5 Q1451.4 1775.63 1450.59 1777.55 Q1449.8 1779.45 1447.69 1782.04 Q1447.11 1782.71 1444.01 1785.93 Q1440.91 1789.12 1435.26 1794.89 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip860)\" d=\"M1946.49 1780.19 Q1949.84 1780.9 1951.72 1783.17 Q1953.62 1785.44 1953.62 1788.77 Q1953.62 1793.89 1950.1 1796.69 Q1946.58 1799.49 1940.1 1799.49 Q1937.92 1799.49 1935.61 1799.05 Q1933.31 1798.64 1930.86 1797.78 L1930.86 1793.27 Q1932.81 1794.4 1935.12 1794.98 Q1937.44 1795.56 1939.96 1795.56 Q1944.36 1795.56 1946.65 1793.82 Q1948.96 1792.08 1948.96 1788.77 Q1948.96 1785.72 1946.81 1784.01 Q1944.68 1782.27 1940.86 1782.27 L1936.83 1782.27 L1936.83 1778.43 L1941.05 1778.43 Q1944.5 1778.43 1946.32 1777.06 Q1948.15 1775.67 1948.15 1773.08 Q1948.15 1770.42 1946.25 1769.01 Q1944.38 1767.57 1940.86 1767.57 Q1938.94 1767.57 1936.74 1767.99 Q1934.54 1768.4 1931.9 1769.28 L1931.9 1765.12 Q1934.56 1764.38 1936.88 1764.01 Q1939.22 1763.64 1941.28 1763.64 Q1946.6 1763.64 1949.7 1766.07 Q1952.81 1768.47 1952.81 1772.59 Q1952.81 1775.46 1951.16 1777.46 Q1949.52 1779.42 1946.49 1780.19 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip860)\" d=\"M2446.88 1768.34 L2435.07 1786.78 L2446.88 1786.78 L2446.88 1768.34 M2445.65 1764.26 L2451.53 1764.26 L2451.53 1786.78 L2456.46 1786.78 L2456.46 1790.67 L2451.53 1790.67 L2451.53 1798.82 L2446.88 1798.82 L2446.88 1790.67 L2431.27 1790.67 L2431.27 1786.16 L2445.65 1764.26 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip860)\" d=\"M1392.08 1844.06 Q1392.08 1845.86 1390.95 1846.89 Q1389.83 1847.89 1388.54 1847.89 Q1387.31 1847.89 1386.67 1847.18 Q1386.03 1846.48 1386.03 1845.57 Q1386.03 1844.35 1386.93 1843.29 Q1387.83 1842.22 1389.18 1842 Q1387.86 1841.16 1385.9 1841.16 Q1384.61 1841.16 1383.48 1841.84 Q1382.39 1842.51 1381.71 1843.38 Q1381.07 1844.25 1380.49 1845.51 Q1379.94 1846.73 1379.71 1847.47 Q1379.52 1848.18 1379.36 1848.96 L1377.1 1857.97 Q1376.01 1862.26 1376.01 1863.77 Q1376.01 1865.64 1376.91 1866.89 Q1377.81 1868.12 1379.62 1868.12 Q1380.32 1868.12 1381.13 1867.93 Q1381.94 1867.7 1382.97 1867.12 Q1384.03 1866.51 1384.96 1865.61 Q1385.93 1864.67 1386.86 1863.09 Q1387.8 1861.52 1388.41 1859.49 Q1388.6 1858.78 1389.25 1858.78 Q1390.05 1858.78 1390.05 1859.42 Q1390.05 1859.97 1389.6 1861.13 Q1389.18 1862.26 1388.25 1863.74 Q1387.35 1865.19 1386.15 1866.51 Q1384.96 1867.8 1383.19 1868.7 Q1381.42 1869.6 1379.49 1869.6 Q1376.72 1869.6 1374.88 1868.12 Q1373.05 1866.64 1372.37 1864.58 Q1372.21 1864.87 1371.98 1865.25 Q1371.76 1865.64 1371.08 1866.51 Q1370.44 1867.35 1369.7 1867.99 Q1368.96 1868.6 1367.8 1869.08 Q1366.67 1869.6 1365.45 1869.6 Q1363.9 1869.6 1362.52 1869.15 Q1361.16 1868.7 1360.2 1867.67 Q1359.23 1866.64 1359.23 1865.22 Q1359.23 1863.64 1360.29 1862.55 Q1361.39 1861.42 1362.87 1861.42 Q1363.8 1861.42 1364.54 1861.97 Q1365.32 1862.51 1365.32 1863.71 Q1365.32 1865.03 1364.42 1866.02 Q1363.51 1867.02 1362.23 1867.28 Q1363.55 1868.12 1365.51 1868.12 Q1367.64 1868.12 1369.31 1866.25 Q1370.99 1864.38 1371.79 1861.26 Q1373.79 1853.75 1374.56 1850.41 Q1375.33 1847.02 1375.33 1845.57 Q1375.33 1844.22 1374.98 1843.29 Q1374.62 1842.35 1374.01 1841.93 Q1373.43 1841.48 1372.89 1841.32 Q1372.37 1841.16 1371.79 1841.16 Q1370.82 1841.16 1369.73 1841.55 Q1368.67 1841.93 1367.38 1842.84 Q1366.12 1843.71 1364.93 1845.51 Q1363.74 1847.31 1362.93 1849.79 Q1362.77 1850.53 1362.06 1850.53 Q1361.29 1850.5 1361.29 1849.86 Q1361.29 1849.31 1361.71 1848.18 Q1362.16 1847.02 1363.06 1845.57 Q1364 1844.12 1365.19 1842.84 Q1366.41 1841.52 1368.18 1840.61 Q1369.99 1839.71 1371.92 1839.71 Q1372.79 1839.71 1373.63 1839.91 Q1374.5 1840.07 1375.53 1840.55 Q1376.59 1841.03 1377.52 1842.1 Q1378.46 1843.16 1379.04 1844.7 Q1379.42 1843.96 1379.94 1843.26 Q1380.49 1842.55 1381.32 1841.68 Q1382.19 1840.78 1383.38 1840.26 Q1384.61 1839.71 1385.96 1839.71 Q1387.28 1839.71 1388.57 1840.07 Q1389.86 1840.39 1390.95 1841.45 Q1392.08 1842.48 1392.08 1844.06 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"115.057,1734.12 115.057,47.2441 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"115.057,1378.36 133.955,1378.36 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"115.057,967.683 133.955,967.683 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"115.057,557.002 133.955,557.002 \"/>\n<polyline clip-path=\"url(#clip860)\" style=\"stroke:#000000; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"115.057,146.321 133.955,146.321 \"/>\n<path clip-path=\"url(#clip860)\" d=\"M54.8299 1391.71 L62.4687 1391.71 L62.4687 1365.34 L54.1586 1367.01 L54.1586 1362.75 L62.4224 1361.08 L67.0983 1361.08 L67.0983 1391.71 L74.7372 1391.71 L74.7372 1395.64 L54.8299 1395.64 L54.8299 1391.71 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip860)\" d=\"M58.4178 981.028 L74.7372 981.028 L74.7372 984.963 L52.7928 984.963 L52.7928 981.028 Q55.4549 978.273 60.0382 973.644 Q64.6446 968.991 65.8252 967.649 Q68.0705 965.125 68.9502 963.389 Q69.8529 961.63 69.8529 959.94 Q69.8529 957.186 67.9085 955.45 Q65.9872 953.713 62.8854 953.713 Q60.6863 953.713 58.2326 954.477 Q55.8021 955.241 53.0243 956.792 L53.0243 952.07 Q55.8484 950.936 58.3021 950.357 Q60.7558 949.778 62.7928 949.778 Q68.1631 949.778 71.3576 952.463 Q74.552 955.149 74.552 959.639 Q74.552 961.769 73.7418 963.69 Q72.9548 965.588 70.8483 968.181 Q70.2696 968.852 67.1678 972.07 Q64.0659 975.264 58.4178 981.028 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip860)\" d=\"M67.6076 555.648 Q70.964 556.366 72.839 558.634 Q74.7372 560.903 74.7372 564.236 Q74.7372 569.352 71.2187 572.152 Q67.7002 574.953 61.2187 574.953 Q59.0428 574.953 56.728 574.514 Q54.4364 574.097 51.9827 573.24 L51.9827 568.727 Q53.9271 569.861 56.2419 570.44 Q58.5567 571.018 61.0798 571.018 Q65.478 571.018 67.7696 569.282 Q70.0844 567.546 70.0844 564.236 Q70.0844 561.18 67.9317 559.467 Q65.802 557.731 61.9826 557.731 L57.9549 557.731 L57.9549 553.889 L62.1678 553.889 Q65.6169 553.889 67.4455 552.523 Q69.2742 551.134 69.2742 548.541 Q69.2742 545.879 67.3761 544.467 Q65.5011 543.032 61.9826 543.032 Q60.0613 543.032 57.8623 543.449 Q55.6632 543.866 53.0243 544.745 L53.0243 540.579 Q55.6864 539.838 58.0012 539.467 Q60.3391 539.097 62.3993 539.097 Q67.7233 539.097 70.8252 541.528 Q73.927 543.935 73.927 548.055 Q73.927 550.926 72.2835 552.916 Q70.64 554.884 67.6076 555.648 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><path clip-path=\"url(#clip860)\" d=\"M65.1539 133.115 L53.3484 151.564 L65.1539 151.564 L65.1539 133.115 M63.927 129.041 L69.8066 129.041 L69.8066 151.564 L74.7372 151.564 L74.7372 155.453 L69.8066 155.453 L69.8066 163.601 L65.1539 163.601 L65.1539 155.453 L49.5521 155.453 L49.5521 150.939 L63.927 129.041 Z\" fill=\"#000000\" fill-rule=\"nonzero\" fill-opacity=\"1\" /><polyline clip-path=\"url(#clip862)\" style=\"stroke:#009af9; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"186.539,94.9858 311.946,120.653 437.353,146.321 562.76,171.988 688.168,197.656 813.575,223.324 938.982,248.991 1064.39,274.659 1189.8,300.326 1315.2,325.994 1440.61,351.662 1566.02,377.329 1691.42,402.997 1816.83,428.664 1942.24,454.332 2067.65,479.999 2193.05,505.667 2318.46,531.335 2443.87,557.002 2569.27,582.67 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#e26f46; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"186.539,1686.38 311.946,1635.04 437.353,1583.71 562.76,1532.37 688.168,1481.03 813.575,1429.7 938.982,1378.36 1064.39,1327.03 1189.8,1275.69 1315.2,1224.36 1440.61,1173.02 1566.02,1121.69 1691.42,1070.35 1816.83,1019.02 1942.24,967.683 2067.65,916.348 2193.05,865.013 2318.46,813.678 2443.87,762.343 2569.27,711.008 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#3da44d; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"437.353,3420.99 437.353,-1639.63 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#3da44d; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"2443.87,3420.99 2443.87,-1639.63 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#c271d2; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"-2410.64,1378.36 5166.45,1378.36 \"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#c271d2; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:1; fill:none\" points=\"-2410.64,146.321 5166.45,146.321 \"/>\n<path clip-path=\"url(#clip862)\" d=\"M437.353 1378.36 L562.76 1378.36 L688.168 1378.36 L813.575 1378.36 L938.982 1378.36 L1064.39 1327.03 L1189.8 1275.69 L1315.2 1224.36 L1440.61 1173.02 L1566.02 1121.69 L1691.42 1070.35 L1816.83 1019.02 L1942.24 967.683 L2067.65 916.348 L2193.05 865.013 L2318.46 813.678 L2443.87 762.343 L2443.87 557.002 L2318.46 531.335 L2193.05 505.667 L2067.65 479.999 L1942.24 454.332 L1816.83 428.664 L1691.42 402.997 L1566.02 377.329 L1440.61 351.662 L1315.2 325.994 L1189.8 300.326 L1064.39 274.659 L938.982 248.991 L813.575 223.324 L688.168 197.656 L562.76 171.988 L437.353 146.321  Z\" fill=\"#0000ff\" fill-rule=\"evenodd\" fill-opacity=\"0.2\"/>\n<polyline clip-path=\"url(#clip862)\" style=\"stroke:#0000ff; stroke-linecap:round; stroke-linejoin:round; stroke-width:4; stroke-opacity:0.2; fill:none\" points=\"437.353,1378.36 562.76,1378.36 688.168,1378.36 813.575,1378.36 938.982,1378.36 1064.39,1327.03 1189.8,1275.69 1315.2,1224.36 1440.61,1173.02 1566.02,1121.69 1691.42,1070.35 1816.83,1019.02 1942.24,967.683 2067.65,916.348 2193.05,865.013 2318.46,813.678 2443.87,762.343 \"/>\n</svg>\n```\n\nFeasible domain for LP in Problem 1. The blue region is the feasible domain and the lines the constraints.\n:::\n:::\n\n\n\nThe intersections of the constraints are $(0, 1), (1, 1), (4, 5/2), (4, 3), (0, 4)$. Evaluating the objective over these candidates gives us an optimal point of $(4, 3)$, with an optimal value of $18$.\n\n### Problem 2 (12 points)\n\nA farmer has access to a pesticide which can be used on corn, soybeans, and wheat fields, and costs $70/kg-yr to apply. The crop yields the farmer can obtain following crop yields by applying varying rates of pesticides to the field are shown in @tbl-yields.\n\n| Application Rate (kg/ha) | Soybean (kg/ha) | Wheat (kg/ha) | Corn (kg/ha) |\n|:----------------------------------:|:---------------:|:-------------:|:------------:|\n| 0 | 2900 | 3500 | 5900 |\n| 1 | 3800 | 4100 | 6700 |\n| 2 | 4400 | 4200 | 7900 |\n: Crop yields from applying varying pesticide rates for Problem 1. {#tbl-yields}\n\nThe costs of production, *excluding pesticides*, for each crop, and selling prices, are shown in @tbl-costs.\n\n| Crop | Production Cost (\\$/ha-yr) | Selling Price (\\$/kg) |\n|:----:|:--------------------------------:|:--------------------:|\n| Soybeans | 350 |  0.36 |\n| Wheat | 280 | 0.27 |\n| Corn | 390 | 0.22 |\n: Costs of crop production, excluding pesticides, and selling prices for each crop. {#tbl-costs}\n\nRecently, environmental authorities have declared that farms cannot have an *average* application rate on soybeans, wheat, and corn which exceeds 0.8, 0.7, and 0.6 kg/ha, respectively. The farmer has asked you for advice on how they should plant crops and apply pesticides to maximize profits over 130 total ha while remaining in regulatory compliance if demand for each crop (which is the maximum the market would buy) this year is 250,000 kg?\n\n#### Problem 2.1\n\nThe first step in formulating the optimization problem is to identify the decision variables. A straightforward set of variables are $S_i$, $C_i$, and $W_i$, where these are the hectares of soybeans, corn, and wheat treated with pesticide rate $i=0, 1, 2$ kg/ha.\n\n::: {.callout-note}\n## Alternative Variable Specifications\n\nWe could also combine these crop variables into a single matrix variable $A_{ji}$, where $j$ is an index for the crop. This would let us specify all of the objectives and constraints using matrix notation, but may make the problem harder to read and debug. The final problem will be equivalent but the writeup may look slightly different.\n:::\n\nNext, let's formulate the optimization problem. The goal is to maximize profit, so we want to calculate the profit associated with any given planting and pesticide strategy. \n\nThe profit from producing soybeans is\n\n  \\begin{align*}\n  &\\overbrace{0.36\\left(2900S_0 + 3800 S_1 + 4400S_2\\right)}^{revenue} - \\overbrace{350\\left(S_0 + S_1 + S_2\\right)}^{production cost} - \\overbrace{70\\left(S_1 + 2S_2\\right)}^{pesticide cost} \\\\\n  &= (1044-350)S_0 + (1368-350-70)S_1 + (1584-350-140)S_2 \\\\\n  &= 694S_0 + 948 S_1 + 1094 S_2.\n  \\end{align*}\n\nSimilarly, the profit from producing wheat is $$665W_0 + 757W_1 + 714W_2$$ and from corn $$908C_0 + 1014C_1 + 1208C_2.$$ So the overall objective is $$\\max_{S_i, W_i, C_i} 694S_0 + 948 S_1 + 1094 S_2 + 665W_0 + 757W_1 + 714W_2 + 908C_0 + 1014C_1 + 1208C_2.$$\n\nFor constraints, we have the non-negativity constraints $$S_i, W_i, C_i \\geq 0.$$ The total planted area cannot exceed 130 ha, so $$S_0+S_1+S_2+C_0+C_1+C_2+W_0+W_1+W_2 \\leq 130.$$ We would also get no revenue from producing more than 250,000 kg of any crop, so we will add that in as a set of constraints:\n\n\\begin{align*}\n2900S_0 + 3800S_1 + 4400S_2 &\\leq 250000 \\\\\n3500W_0 + 4100W_1 + 4200W_2 &\\leq 250000 \\\\\n5900C_0 + 6700C_1 + 7900C_2 &\\leq 250000.\n\\end{align*}\n\nFinally, we have the pesticide application constraints. These are a little tricky because the most direct way of writing them down does not result in a linear constraint, so we will need to do some algebra. Let's illustrate this with the soybean constraint. The average application rate cannot exceed 0.8 kg/ha, which means $$\\frac{S_1 + 2S_2}{S_0 + S_1 + S_2} \\leq 0.8.$$ As noted, this is not linear, but we can turn it into a linear constraint by multiplying through by $S_0+S_1+S_2$ and moving everything over to the left-hand side. This yields $$-0.8S_0 + 0.2S_1 + 1.2S_2 \\leq 0.$$ Similarly, the wheat and corn constraints are, respectively,\n\n\\begin{align*}\n-0.7W_0 + 0.3 W_1 + 1.3 W_2 &\\leq 0 \\\\\n-0.6C_0 + 0.4C_1 + 1.4C_2 & \\leq 0.\n\\end{align*}\n\nThus our final linear program is:\n\n$$\n\\begin{alignedat}{2}\n& \\max_{S_i, W_i, C_i} \\quad &&694S_0 + 948 S_1 + 1094 S_2 + 665W_0 + 757W_1 + 714W_2 + 908C_0 + 1014C_1 + 1208C_2\\\\\n&\\text{subject to:} \\quad && 2900S_0 + 3800S_1 + 4400S_2 \\leq 250000\\\\\n& && 3500W_0 + 4100W_1 + 4200W_2 \\leq 250000\\\\\n& && 5900C_0 + 6700C_1 + 7900C_2 \\leq 250000\\\\\n& && -0.8S_0 + 0.2S_1 + 1.2S_2 \\leq 0\\\\\n& && -0.7W_0 + 0.3 W_1 + 1.3 W_2 \\leq 0\\\\\n& && -0.6C_0 + 0.4C_1 + 1.4C_2 \\leq 0\\\\\n& && S_i, W_i, C_i \\geq 0.\n\\end{alignedat}\n$$\n\n#### Problem 2.2\n\nLet's implement this program in `JuMP`. We will use matrix-vector notation for our implementation, but you could also write out the constraints one variable at a time as well; the disadvantage of this is that it does not scale well as the number of variables increases.\n\n::: {#8 .cell execution_count=1}\n``` {.julia .cell-code}\ncrop_model = Model(HiGHS.Optimizer)\n@variable(crop_model, S[1:3] >= 0) # <1>\n@variable(crop_model, W[1:3] >= 0) # <1>\n@variable(crop_model, C[1:3] >= 0) # <1>\n@objective(crop_model, Max, [694; 948; 1094]' * S + [665; 757; 714]' * W + [908; 1014; 1208]' * C) # <2>\n@constraint(crop_model, land, sum(S) + sum(W) + sum(C) <= 130)\n@constraint(crop_model, soy_demand, [2900; 3800; 4400]' * S <= 250_000)\n@constraint(crop_model, wheat_demand, [3500; 4100; 4200]' * W <= 250_000)\n@constraint(crop_model, corn_demand, [5900; 6700; 7900]' * C <= 250_000)\n@constraint(crop_model, soy_pesticide, [-0.8; 0.2; 1.2]' * S <= 0)\n@constraint(crop_model, wheat_pesticide, [-0.7; 0.3; 1.3]' * W <= 0)\n@constraint(crop_model, corn_pesticide, [-0.6; 0.4; 1.4]' * C <= 0)\nprint(crop_model) # <3>\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMax 694 S[1] + 948 S[2] + 1094 S[3] + 665 W[1] + 757 W[2] + 714 W[3] + 908 C[1] + 1014 C[2] + 1208 C[3]\nSubject to\n land : S[1] + S[2] + S[3] + W[1] + W[2] + W[3] + C[1] + C[2] + C[3] ≤ 130\n soy_demand : 2900 S[1] + 3800 S[2] + 4400 S[3] ≤ 250000\n wheat_demand : 3500 W[1] + 4100 W[2] + 4200 W[3] ≤ 250000\n corn_demand : 5900 C[1] + 6700 C[2] + 7900 C[3] ≤ 250000\n soy_pesticide : -0.8 S[1] + 0.2 S[2] + 1.2 S[3] ≤ 0\n wheat_pesticide : -0.7 W[1] + 0.3 W[2] + 1.3 W[3] ≤ 0\n corn_pesticide : -0.6 C[1] + 0.4 C[2] + 1.4 C[3] ≤ 0\n S[1] ≥ 0\n S[2] ≥ 0\n S[3] ≥ 0\n W[1] ≥ 0\n W[2] ≥ 0\n W[3] ≥ 0\n C[1] ≥ 0\n C[2] ≥ 0\n C[3] ≥ 0\n```\n:::\n:::\n\n\n1. Even though we defined the indices $i$ to start at 0, Julia's indexing starts at 1, so we will need to bear that in mind when we formulate the problem and interpret the solution.\n2. When using matrix-vector syntax, be careful about the dimensions and making sure they match; any mistakes should come out as you formulate the model and print it out, but may be hard to tell if the problem is sufficiently large. You could also directly compute the dot product with syntax like `sum([694; 948; 1094] .* S)`.\n3. I would always `print` your model just to make sure there are no obvious typos. I made one while writing up the solution and printing the model let me see it! \n\nNow, let's find the solution.\n\n::: {#10 .cell execution_count=1}\n``` {.julia .cell-code}\noptimize!(crop_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRunning HiGHS 1.7.2 (git hash: 5ce7a2753): Copyright (c) 2024 HiGHS under MIT licence terms\nCoefficient ranges:\n  Matrix [2e-01, 8e+03]\n  Cost   [7e+02, 1e+03]\n  Bound  [0e+00, 0e+00]\n  RHS    [1e+02, 2e+05]\nPresolving model\n7 rows, 9 cols, 27 nonzeros  0s\n7 rows, 9 cols, 27 nonzeros  0s\nPresolve : Reductions: rows 7(-0); columns 9(-0); elements 27(-0) - Not reduced\nProblem not reduced by presolve: solving the LP\nUsing EKK dual simplex solver - serial\n  Iteration        Objective     Infeasibilities num(sum)\n          0    -1.8170297740e+02 Ph1: 7(28.3601); Du: 9(181.703) 0s\n          7     1.1674116702e+05 Pr: 0(0) 0s\nModel   status      : Optimal\nSimplex   iterations: 7\nObjective value     :  1.1674116702e+05\nHiGHS run time      :          0.00\n```\n:::\n:::\n\n\n\nWe found a solution, which is a good sign that we didn't mis-specify our constraints (which can result in an unbounded problem, which would throw an error). The optimal planting and pesticide strategy is then:\n\n::: {#12 .cell execution_count=1}\n``` {.julia .cell-code}\n@show value.(S);\n@show value.(W);\n@show value.(C);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvalue.(S) = [13.812154696132604, 55.24861878453038, 0.0]\nvalue.(W) = [6.7433064173395625, 15.734381640458977, 0.0]\nvalue.(C) = [26.92307692307692, 0.0, 11.538461538461547]\n```\n:::\n:::\n\n\n\nSummarizing in a table:\n\n| Pesticide Rate (kg/ha) | Soy Area (ha) | Corn Area (ha) | Wheat Area (ha) |\n|:------:|---------:|---------:|---------:|\n| 0 | 13.8 | 6.7 | 26.9 |\n| 1 | 55.2 | 15.7 | 0 |\n| 2 | 0 | 0 | 11.5 |\n\nThe resulting profit is:\n\n::: {#14 .cell execution_count=1}\n``` {.julia .cell-code}\n@show round(objective_value(crop_model); digits=0);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nround(objective_value(crop_model); digits = 0) = 116741.0\n```\n:::\n:::\n\n\n\n\n#### Problem 2.3\n\nTo evaluate whether the farmer should buy the land, we can look at the shadow price.\n\n::: {#16 .cell execution_count=1}\n``` {.julia .cell-code}\n@show shadow_price(land);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshadow_price(land) = 729.4\n```\n:::\n:::\n\n\n\nThe shadow price is non-zero, so the land constraint is binding and the farmer could make more money by buying land. Since the amount of land is relatively small, we can take the shadow price and multiply it by 10 to get an estimate of the value to the farmer of buying the land, which is approximately \\$7294.\n\nDoes this result make sense? Looking at the other constraints, wheat is the only crop for which the demand constraint isn't binding, so any additional land would have to be used to grow wheat. From the solution, it seems clear that there is no point in increasing $W_2$, as wheat treated with two kg/ha of pesticide is less profitable than wheat treated with one, and the additional pesticide would limit the amount we could grow. As the wheat pesticide constraint is already binding, to stay in compliance we would need to allocate no more than 7 ha to $W_1$ and 3 ha to $W_2$ based on the constraint. And then if we plug those values into the wheat profit equation that went into our objective, $\\$757 \\times 7 + \\$665 \\times 3 = \\$7294$, which is the same as the additional profit we estimated using the shadow price.\n\n\n### Problem 3 (15 points)\n\n#### Problem 3.1\n\nFrom lecture, the decision variables for a \"greenfield\" capacity expansion are:\n\n* $x_g$: capacity installed (MW) for generator type $g$;\n* $y_{g,t}$: generated power (MWh) by generator type $g$ in hour $t$;\n* $NSE_t$: non-served demand (MWh) in hour $t$.\n\nWe have one new constraint: the CO<sub>2</sub> limit. Let $emis_g$ be the CO~2~ emissions factor (tCO~2~/MWh generated) for plant $g$. Then this constraint is:\n$$\\sum_{g \\in G} emis_g \\times \\sum_{t \\in T} y_{g,t} \\leq 1,500,000.$$\n\nThe optimization problem is:\n\n\\begin{align*}\n\\min_{x, y, NSE} \\quad & \\sum_{g \\in \\mathcal{G}} \\text{FixedCost}_g \\times x_g + \\sum_{t \\in \\mathcal{T}} \\sum_{g \\in \\mathcal{G}} \\text{VarCost}_g \\times y_{g,t} & \\\\\n& \\quad + \\sum_{t \\in \\mathcal{T}} \\text{NSECost} \\times NSE_t & \\\\\n\\text {subject to:} \\quad & \\sum_{g \\in \\mathcal{G}} y_{g,t} + NSE_t = d_t \\qquad \\qquad \\forall t \\in \\mathcal{T} \\\\\n& y_{g,t} \\leq x_g \\times c_{g,t} \\qquad \\qquad \\qquad\\qquad  \\forall g \\in {G},  \\forall t \\in \\mathcal{T} \\\\\n& \\sum_{g \\in G} emis_g \\times \\sum_{t \\in T} y_{g,t} \\leq 1,500,000 \\\\\n& x_g, y_{g,t}, NSE_t \\geq 0 \\qquad \\qquad \\qquad \\forall g \\in {G},  \\forall t \\in \\mathcal{T},\n\\end{align*}\n\nwhere $d_t$ is the demand in hour $t$, and $c_{g,t}$ is the capacity factor in hour $t$ for generator class $g$.\n\n#### Problem 3.2\n\nFirst, let's load the data for demand, the generators, and renewable variability.\n\n::: {#18 .cell execution_count=1}\n``` {.julia .cell-code}\n# load the data, pull Zone C, and reformat the DataFrame\nNY_demand = DataFrame(CSV.File(\"data/2013_hourly_load_NY.csv\")) # <1>\nrename!(NY_demand, :\"Time Stamp\" => :Date)\ndemand = NY_demand[:, [:Date, :C]]\nrename!(demand, :C => :Demand)\ndemand[:, :Hour] = 1:nrow(demand)\n\n# generator data\ngens = DataFrame(CSV.File(\"data/generators.csv\")) # <1>\n\n# load capacify factors into a DataFrame\ncap_factor = DataFrame(CSV.File(\"data/wind_solar_capacity_factors.csv\")) # <1>\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>8760×3 DataFrame</span></div><div style = \"float: right;\"><span style = \"font-style: italic;\">8735 rows omitted</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"header\"><th class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Hour</th><th style = \"text-align: left;\">Wind</th><th style = \"text-align: left;\">Solar</th></tr><tr class = \"subheader headerLastRow\"><th class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">0.0456225</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">0.0908019</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">0.177524</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">0.196106</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: right;\">5</td><td style = \"text-align: right;\">0.163481</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: right;\">6</td><td style = \"text-align: right;\">0.129312</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">7</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">0.131448</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8</td><td style = \"text-align: right;\">8</td><td style = \"text-align: right;\">0.162792</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">9</td><td style = \"text-align: right;\">9</td><td style = \"text-align: right;\">0.341911</td><td style = \"text-align: right;\">0.115556</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">10</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">0.222848</td><td style = \"text-align: right;\">0.530593</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">11</td><td style = \"text-align: right;\">11</td><td style = \"text-align: right;\">0.030222</td><td style = \"text-align: right;\">0.747114</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">12</td><td style = \"text-align: right;\">12</td><td style = \"text-align: right;\">0.0143295</td><td style = \"text-align: right;\">0.874793</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">13</td><td style = \"text-align: right;\">13</td><td style = \"text-align: right;\">0.0377381</td><td style = \"text-align: right;\">0.94319</td></tr><tr><td style = \"text-align: right;\">&vellip;</td><td style = \"text-align: right;\">&vellip;</td><td style = \"text-align: right;\">&vellip;</td><td style = \"text-align: right;\">&vellip;</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8749</td><td style = \"text-align: right;\">8749</td><td style = \"text-align: right;\">0.284942</td><td style = \"text-align: right;\">0.734762</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8750</td><td style = \"text-align: right;\">8750</td><td style = \"text-align: right;\">0.462101</td><td style = \"text-align: right;\">0.643106</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8751</td><td style = \"text-align: right;\">8751</td><td style = \"text-align: right;\">0.327947</td><td style = \"text-align: right;\">0.632685</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8752</td><td style = \"text-align: right;\">8752</td><td style = \"text-align: right;\">0.249119</td><td style = \"text-align: right;\">0.560314</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8753</td><td style = \"text-align: right;\">8753</td><td style = \"text-align: right;\">0.171991</td><td style = \"text-align: right;\">0.445911</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8754</td><td style = \"text-align: right;\">8754</td><td style = \"text-align: right;\">0.234215</td><td style = \"text-align: right;\">0.232936</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8755</td><td style = \"text-align: right;\">8755</td><td style = \"text-align: right;\">0.32073</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8756</td><td style = \"text-align: right;\">8756</td><td style = \"text-align: right;\">0.166379</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8757</td><td style = \"text-align: right;\">8757</td><td style = \"text-align: right;\">0.252252</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8758</td><td style = \"text-align: right;\">8758</td><td style = \"text-align: right;\">0.276054</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8759</td><td style = \"text-align: right;\">8759</td><td style = \"text-align: right;\">0.111131</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">8760</td><td style = \"text-align: right;\">8760</td><td style = \"text-align: right;\">0.208158</td><td style = \"text-align: right;\">0.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n1. We load these tabular files into a `DataFrame` to improve our ability to manipulate them.\n\n\nTo put this into `JuMP`, the our first task is to decide how we want to handle the difference between the renewable generating technologies (which have time-varying capacity factors) and the thermal technologies (which have constant capacity factors). We can either create a joint capacity factor `DataFrame` which we can then use to construct all of our capacity constraints, or we can create two different capacity constraints, one for renewables and one for non-renewables. The eventual problem will be the same, but the code would look slightly different. In this solution, we will take the former approach to show what it looks like.\n\nTo construct a single capacity factor `DataFrame`:\n\n::: {#20 .cell execution_count=1}\n``` {.julia .cell-code}\n# define sets\nG = 1:nrow(gens) # <1>\nT = 1:nrow(demand) # <1>\n\n# capacity factor matrix\ncf_constant = ones(T[end], G[end-2]) # <2>\n# set geothermal capacity\ncf_constant[:, 1] .= 0.85 # <3>\n# append wind and solar capacity factors\ncf = hcat(cf_constant, cap_factor[!, :Wind], cap_factor[!, :Solar]) # <4>\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n8760×6 Matrix{Float64}:\n 0.85  1.0  1.0  1.0  0.0456225  0.0\n 0.85  1.0  1.0  1.0  0.0908019  0.0\n 0.85  1.0  1.0  1.0  0.177524   0.0\n 0.85  1.0  1.0  1.0  0.196106   0.0\n 0.85  1.0  1.0  1.0  0.163481   0.0\n 0.85  1.0  1.0  1.0  0.129312   0.0\n 0.85  1.0  1.0  1.0  0.131448   0.0\n 0.85  1.0  1.0  1.0  0.162792   0.0\n 0.85  1.0  1.0  1.0  0.341911   0.115556\n 0.85  1.0  1.0  1.0  0.222848   0.530593\n ⋮                               ⋮\n 0.85  1.0  1.0  1.0  0.249119   0.560314\n 0.85  1.0  1.0  1.0  0.171991   0.445911\n 0.85  1.0  1.0  1.0  0.234215   0.232936\n 0.85  1.0  1.0  1.0  0.32073    0.0\n 0.85  1.0  1.0  1.0  0.166379   0.0\n 0.85  1.0  1.0  1.0  0.252252   0.0\n 0.85  1.0  1.0  1.0  0.276054   0.0\n 0.85  1.0  1.0  1.0  0.111131   0.0\n 0.85  1.0  1.0  1.0  0.208158   0.0\n```\n:::\n:::\n\n\n1. We need to define these index sets in any case to help set up arrays of constraints (we don't, for example, want to define all of the individual demand constraints for every hour individually).\n2. The last two generators in the `gens` DataFrame are solar and wind, so we want to drop those as we will replace them with the varying capacity factor data that we loaded. The `end` keyword is just syntax to automate looking up the last index, so we can just subtract values from it.\n3. We broadcast the `=` operator to assign element-wise; Julia will throw an error if we try to assign a scalar to a vector because it doesn't know if we want to do element-wise assigning or if this is an error. Requiring broadcasting forces us to be explicit about our intent.\n4. You can use either `cap_factor[!, :Wind]` or `cap_factor[:, :Wind]` to refer to a \"slice\" of the DataFrame with column name `Wind`. The difference is that `!` does not allocate a temporary DataFrame, which makes it more memory efficient but also means it can't be manipulated. You could also use a column index number instead of the name if you didn't have meaningful names or didn't know what they were.\n\nNow we can implement our model.\n\n::: {#22 .cell execution_count=1}\n``` {.julia .cell-code}\n# define NSECost\nNSECost = 10_000\n\n# set up model object\ngencap = Model(HiGHS.Optimizer) # use the HiGHS LP solver\n\n# define variables\n@variable(gencap, x[g in G] >= 0) # installed capacity\n@variable(gencap, y[g in G, t in T] >= 0) # generated power\n@variable(gencap, nse[t in T] >= 0) # unserved energy\n\n# define objective: minimize sum of fixed costs, variable costs of generation, \n# and non-served energy penalty\n@objective(gencap, Min, sum(gens[!, :FixedCost] .* x) + \n    sum(gens[!, :VarCost] .* [sum(y[g, :]) for g in G]) + \n    NSECost * sum(nse))\n\n# define constraints\n@constraint(gencap, capacity[g in G, t in T], y[g, t] <= x[g] * cf[t, g]) # capacity constraint\n@constraint(gencap, demand_met[t in T], sum(y[:, t]) + nse[t] >= demand.Demand[t]) # demand constraint\n@constraint(gencap, co2, sum(gens[:, :Emissions] .* [sum(y[g, :]) for g in G]) <= 1500000) # co2 constraint\nprint(gencap) # <1>\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMin 450000 x[1] + 220000 x[2] + 82000 x[3] + 65000 x[4] + 91000 x[5] + 70000 x[6] + 24 y[2,1] + 24 y[2,2] + 24 y[2,3] + 24 y[2,4] + 24 y[2,5] + 24 y[2,6] + 24 y[2,7] + 24 y[2,8] + 24 y[2,9] + 24 y[2,10] + 24 y[2,11] + 24 y[2,12] + 24 y[2,13] + 24 y[2,14] + 24 y[2,15] + 24 y[2,16] + 24 y[2,17] + 24 y[2,18] + 24 y[2,19] + 24 y[2,20] + 24 y[2,21] + 24 y[2,22] + 24 y[2,23] + 24 y[2,24] + [[...34986 terms omitted...]] + 10000 nse[8731] + 10000 nse[8732] + 10000 nse[8733] + 10000 nse[8734] + 10000 nse[8735] + 10000 nse[8736] + 10000 nse[8737] + 10000 nse[8738] + 10000 nse[8739] + 10000 nse[8740] + 10000 nse[8741] + 10000 nse[8742] + 10000 nse[8743] + 10000 nse[8744] + 10000 nse[8745] + 10000 nse[8746] + 10000 nse[8747] + 10000 nse[8748] + 10000 nse[8749] + 10000 nse[8750] + 10000 nse[8751] + 10000 nse[8752] + 10000 nse[8753] + 10000 nse[8754] + 10000 nse[8755] + 10000 nse[8756] + 10000 nse[8757] + 10000 nse[8758] + 10000 nse[8759] + 10000 nse[8760]\nSubject to\n demand_met[1] : y[1,1] + y[2,1] + y[3,1] + y[4,1] + y[5,1] + y[6,1] + nse[1] ≥ 1678.3\n demand_met[2] : y[1,2] + y[2,2] + y[3,2] + y[4,2] + y[5,2] + y[6,2] + nse[2] ≥ 1596.7\n demand_met[3] : y[1,3] + y[2,3] + y[3,3] + y[4,3] + y[5,3] + y[6,3] + nse[3] ≥ 1522.8\n demand_met[4] : y[1,4] + y[2,4] + y[3,4] + y[4,4] + y[5,4] + y[6,4] + nse[4] ≥ 1497.7\n demand_met[5] : y[1,5] + y[2,5] + y[3,5] + y[4,5] + y[5,5] + y[6,5] + nse[5] ≥ 1507.8\n demand_met[6] : y[1,6] + y[2,6] + y[3,6] + y[4,6] + y[5,6] + y[6,6] + nse[6] ≥ 1540.2\n demand_met[7] : y[1,7] + y[2,7] + y[3,7] + y[4,7] + y[5,7] + y[6,7] + nse[7] ≥ 1591.2\n demand_met[8] : y[1,8] + y[2,8] + y[3,8] + y[4,8] + y[5,8] + y[6,8] + nse[8] ≥ 1657.3\n demand_met[9] : y[1,9] + y[2,9] + y[3,9] + y[4,9] + y[5,9] + y[6,9] + nse[9] ≥ 1677.1\n demand_met[10] : y[1,10] + y[2,10] + y[3,10] + y[4,10] + y[5,10] + y[6,10] + nse[10] ≥ 1809.6\n demand_met[11] : y[1,11] + y[2,11] + y[3,11] + y[4,11] + y[5,11] + y[6,11] + nse[11] ≥ 1895.5\n demand_met[12] : y[1,12] + y[2,12] + y[3,12] + y[4,12] + y[5,12] + y[6,12] + nse[12] ≥ 1944.6\n demand_met[13] : y[1,13] + y[2,13] + y[3,13] + y[4,13] + y[5,13] + y[6,13] + nse[13] ≥ 1959.4\n demand_met[14] : y[1,14] + y[2,14] + y[3,14] + y[4,14] + y[5,14] + y[6,14] + nse[14] ≥ 1949.8\n demand_met[15] : y[1,15] + y[2,15] + y[3,15] + y[4,15] + y[5,15] + y[6,15] + nse[15] ≥ 1937.2\n demand_met[16] : y[1,16] + y[2,16] + y[3,16] + y[4,16] + y[5,16] + y[6,16] + nse[16] ≥ 1952\n demand_met[17] : y[1,17] + y[2,17] + y[3,17] + y[4,17] + y[5,17] + y[6,17] + nse[17] ≥ 2061.4\n demand_met[18] : y[1,18] + y[2,18] + y[3,18] + y[4,18] + y[5,18] + y[6,18] + nse[18] ≥ 2256.4\n demand_met[19] : y[1,19] + y[2,19] + y[3,19] + y[4,19] + y[5,19] + y[6,19] + nse[19] ≥ 2273.7\n demand_met[20] : y[1,20] + y[2,20] + y[3,20] + y[4,20] + y[5,20] + y[6,20] + nse[20] ≥ 2251.9\n demand_met[21] : y[1,21] + y[2,21] + y[3,21] + y[4,21] + y[5,21] + y[6,21] + nse[21] ≥ 2176.5\n demand_met[22] : y[1,22] + y[2,22] + y[3,22] + y[4,22] + y[5,22] + y[6,22] + nse[22] ≥ 2038.5\n demand_met[23] : y[1,23] + y[2,23] + y[3,23] + y[4,23] + y[5,23] + y[6,23] + nse[23] ≥ 1908.9\n demand_met[24] : y[1,24] + y[2,24] + y[3,24] + y[4,24] + y[5,24] + y[6,24] + nse[24] ≥ 1800.1\n demand_met[25] : y[1,25] + y[2,25] + y[3,25] + y[4,25] + y[5,25] + y[6,25] + nse[25] ≥ 1742.2\n demand_met[26] : y[1,26] + y[2,26] + y[3,26] + y[4,26] + y[5,26] + y[6,26] + nse[26] ≥ 1711.9\n demand_met[27] : y[1,27] + y[2,27] + y[3,27] + y[4,27] + y[5,27] + y[6,27] + nse[27] ≥ 1665.7\n demand_met[28] : y[1,28] + y[2,28] + y[3,28] + y[4,28] + y[5,28] + y[6,28] + nse[28] ≥ 1690.1\n demand_met[29] : y[1,29] + y[2,29] + y[3,29] + y[4,29] + y[5,29] + y[6,29] + nse[29] ≥ 1741.1\n demand_met[30] : y[1,30] + y[2,30] + y[3,30] + y[4,30] + y[5,30] + y[6,30] + nse[30] ≥ 1864\n demand_met[31] : y[1,31] + y[2,31] + y[3,31] + y[4,31] + y[5,31] + y[6,31] + nse[31] ≥ 2115.1\n demand_met[32] : y[1,32] + y[2,32] + y[3,32] + y[4,32] + y[5,32] + y[6,32] + nse[32] ≥ 2253.2\n demand_met[33] : y[1,33] + y[2,33] + y[3,33] + y[4,33] + y[5,33] + y[6,33] + nse[33] ≥ 2279\n demand_met[34] : y[1,34] + y[2,34] + y[3,34] + y[4,34] + y[5,34] + y[6,34] + nse[34] ≥ 2287.7\n demand_met[35] : y[1,35] + y[2,35] + y[3,35] + y[4,35] + y[5,35] + y[6,35] + nse[35] ≥ 2294.8\n demand_met[36] : y[1,36] + y[2,36] + y[3,36] + y[4,36] + y[5,36] + y[6,36] + nse[36] ≥ 2298.5\n demand_met[37] : y[1,37] + y[2,37] + y[3,37] + y[4,37] + y[5,37] + y[6,37] + nse[37] ≥ 2256.7\n demand_met[38] : y[1,38] + y[2,38] + y[3,38] + y[4,38] + y[5,38] + y[6,38] + nse[38] ≥ 2243.1\n demand_met[39] : y[1,39] + y[2,39] + y[3,39] + y[4,39] + y[5,39] + y[6,39] + nse[39] ≥ 2225.4\n demand_met[40] : y[1,40] + y[2,40] + y[3,40] + y[4,40] + y[5,40] + y[6,40] + nse[40] ≥ 2231.1\n demand_met[41] : y[1,41] + y[2,41] + y[3,41] + y[4,41] + y[5,41] + y[6,41] + nse[41] ≥ 2314.8\n demand_met[42] : y[1,42] + y[2,42] + y[3,42] + y[4,42] + y[5,42] + y[6,42] + nse[42] ≥ 2485.7\n demand_met[43] : y[1,43] + y[2,43] + y[3,43] + y[4,43] + y[5,43] + y[6,43] + nse[43] ≥ 2496.4\n demand_met[44] : y[1,44] + y[2,44] + y[3,44] + y[4,44] + y[5,44] + y[6,44] + nse[44] ≥ 2464.4\n demand_met[45] : y[1,45] + y[2,45] + y[3,45] + y[4,45] + y[5,45] + y[6,45] + nse[45] ≥ 2404.2\n demand_met[46] : y[1,46] + y[2,46] + y[3,46] + y[4,46] + y[5,46] + y[6,46] + nse[46] ≥ 2273.9\n demand_met[47] : y[1,47] + y[2,47] + y[3,47] + y[4,47] + y[5,47] + y[6,47] + nse[47] ≥ 2111.4\n demand_met[48] : y[1,48] + y[2,48] + y[3,48] + y[4,48] + y[5,48] + y[6,48] + nse[48] ≥ 1974.8\n demand_met[49] : y[1,49] + y[2,49] + y[3,49] + y[4,49] + y[5,49] + y[6,49] + nse[49] ≥ 1882.9\n demand_met[50] : y[1,50] + y[2,50] + y[3,50] + y[4,50] + y[5,50] + y[6,50] + nse[50] ≥ 1835.7\n[[...122547 constraints skipped...]]\n nse[8711] ≥ 0\n nse[8712] ≥ 0\n nse[8713] ≥ 0\n nse[8714] ≥ 0\n nse[8715] ≥ 0\n nse[8716] ≥ 0\n nse[8717] ≥ 0\n nse[8718] ≥ 0\n nse[8719] ≥ 0\n nse[8720] ≥ 0\n nse[8721] ≥ 0\n nse[8722] ≥ 0\n nse[8723] ≥ 0\n nse[8724] ≥ 0\n nse[8725] ≥ 0\n nse[8726] ≥ 0\n nse[8727] ≥ 0\n nse[8728] ≥ 0\n nse[8729] ≥ 0\n nse[8730] ≥ 0\n nse[8731] ≥ 0\n nse[8732] ≥ 0\n nse[8733] ≥ 0\n nse[8734] ≥ 0\n nse[8735] ≥ 0\n nse[8736] ≥ 0\n nse[8737] ≥ 0\n nse[8738] ≥ 0\n nse[8739] ≥ 0\n nse[8740] ≥ 0\n nse[8741] ≥ 0\n nse[8742] ≥ 0\n nse[8743] ≥ 0\n nse[8744] ≥ 0\n nse[8745] ≥ 0\n nse[8746] ≥ 0\n nse[8747] ≥ 0\n nse[8748] ≥ 0\n nse[8749] ≥ 0\n nse[8750] ≥ 0\n nse[8751] ≥ 0\n nse[8752] ≥ 0\n nse[8753] ≥ 0\n nse[8754] ≥ 0\n nse[8755] ≥ 0\n nse[8756] ≥ 0\n nse[8757] ≥ 0\n nse[8758] ≥ 0\n nse[8759] ≥ 0\n nse[8760] ≥ 0\n```\n:::\n:::\n\n\n1. Notice that here we've hit the limit of what we can read directly from the model printing, but hopefully it gives us an idea of how everything looks.\n\nNow we optimize.\n\n::: {#24 .cell execution_count=1}\n``` {.julia .cell-code}\noptimize!(gencap)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRunning HiGHS 1.7.2 (git hash: 5ce7a2753): Copyright (c) 2024 HiGHS under MIT licence terms\nCoefficient ranges:\n  Matrix [5e-05, 1e+00]\n  Cost   [2e+01, 4e+05]\n  Bound  [0e+00, 0e+00]\n  RHS    [1e+03, 2e+06]\nPresolving model\n56857 rows, 56862 cols, 179328 nonzeros  0s\n56854 rows, 56859 cols, 179322 nonzeros  0s\nPresolve : Reductions: rows 56854(-4467); columns 56859(-4467); elements 179322(-8934)\nSolving the presolved LP\nUsing EKK dual simplex solver - serial\n  Iteration        Objective     Infeasibilities num(sum)\n          0     0.0000000000e+00 Pr: 8760(4.11193e+06) 0s\n      27739     7.3475471138e+08 Pr: 20210(1.04615e+07); Du: 0(3.47475e-06) 5s\n      36116     7.8535120736e+08 Pr: 123(252.985); Du: 0(8.18449e-06) 10s\n      36200     7.8535295894e+08 Pr: 0(0); Du: 0(2.3938e-13) 11s\nSolving the original LP from the solution after postsolve\nModel   status      : Optimal\nSimplex   iterations: 36200\nObjective value     :  7.8535295894e+08\nHiGHS run time      :         10.62\n```\n:::\n:::\n\n\n\nWe can find how much generating capacity we want to build for each plant type by querying the relevant decision variable `x`. We will turn this into a DataFrame to make the presentation easier.\n\n::: {#26 .cell execution_count=1}\n``` {.julia .cell-code}\nbuilt_cap = value.(x).data\nDataFrame(Plant=gens.Plant, Capacity=round.(built_cap; digits=0))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×2 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"header\"><th class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Plant</th><th style = \"text-align: left;\">Capacity</th></tr><tr class = \"subheader headerLastRow\"><th class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"InlineStrings.String15\" style = \"text-align: left;\">String15</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Geothermal</td><td style = \"text-align: right;\">286.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Coal</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">NG CCGT</td><td style = \"text-align: right;\">1509.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">NG CT</td><td style = \"text-align: right;\">703.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Wind</td><td style = \"text-align: right;\">2549.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Solar</td><td style = \"text-align: right;\">2104.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nSimilarly, we can find the total amount of non-served energy by adding up `nse[t]`.\n\n::: {#28 .cell execution_count=1}\n``` {.julia .cell-code}\n@show sum(value.(nse).data);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsum(value.(nse).data) = 332.2907137925944\n```\n:::\n:::\n\n\n\nSo this plan results in 332 MWh of non-served energy throughout the year. \n\nFinally, to get the total cost of the system we use `objective_value`:\n\n::: {#30 .cell execution_count=1}\n``` {.julia .cell-code}\n@show objective_value(gencap);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nobjective_value(gencap) = 7.853529589434922e8\n```\n:::\n:::\n\n\n\nSo the cost of building and operating this system (fixed and variable costs) for a year is \\$7\\.9e8.\n\n#### Problem 3.3\n\nTo find the total annual generation from each plant, we want to sum up the values of the variable `y` along the time dimension.\n\n::: {#32 .cell execution_count=1}\n``` {.julia .cell-code}\nannual_gen = [sum(value.(y[g, :]).data) for g in G]\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n6-element Vector{Float64}:\n      1.1094868959605992e6\n      0.0\n      3.3227665594545454e6\n 129473.41715377253\n      6.6147067325310875e6\n      5.191140004186203e6\n```\n:::\n:::\n\n\n\nNotice that this means that the cost of the system per MWh generated is \\$48/MWh.\n\nWe can then convert this into fractions of total generation, which we can compare to fractions of built capacity.\n\n::: {#34 .cell execution_count=1}\n``` {.julia .cell-code}\nannual_gen_frac = annual_gen ./ sum(annual_gen)\nbuilt_frac = built_cap ./ sum(built_cap)\nDataFrame(Plant=gens[!, :Plant], Built_Perc=100 * round.(built_frac; digits=2), Generated_Perc=100 * round.(annual_gen_frac; digits=2))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div><div style = \"float: left;\"><span>6×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"header\"><th class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Plant</th><th style = \"text-align: left;\">Built_Perc</th><th style = \"text-align: left;\">Generated_Perc</th></tr><tr class = \"subheader headerLastRow\"><th class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"InlineStrings.String15\" style = \"text-align: left;\">String15</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Geothermal</td><td style = \"text-align: right;\">4.0</td><td style = \"text-align: right;\">7.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Coal</td><td style = \"text-align: right;\">0.0</td><td style = \"text-align: right;\">0.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">NG CCGT</td><td style = \"text-align: right;\">21.0</td><td style = \"text-align: right;\">20.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">NG CT</td><td style = \"text-align: right;\">10.0</td><td style = \"text-align: right;\">1.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">Wind</td><td style = \"text-align: right;\">36.0</td><td style = \"text-align: right;\">40.0</td></tr><tr><td class = \"rowNumber\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">Solar</td><td style = \"text-align: right;\">29.0</td><td style = \"text-align: right;\">32.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nOne observation is that that we have to overbuild the fraction of combustion turbine gas plants (NG CT) relative to the fraction of times in which they are used, as these are needed when wind and solar is low, but otherwise are less commonly used. We also have to slightly underbuild wind and solar relative to the power generated by these technologies, as they are free to generate and so will be operated whenever their resources allow.\n\n\n#### Problem 3.5\n\nTo find the value to the utility of relaxing the CO~2~ constraint, we can use the shadow price:\n\n::: {#36 .cell execution_count=1}\n``` {.julia .cell-code}\n@show shadow_price(co2);\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshadow_price(co2) = -182.77193609185863\n```\n:::\n:::\n\n\n\nWhy does it make sense that this shadow price is negative? Remember that a shadow price is the change in the objective relative to \"relaxing\" the constraint: in other words, what is the change in the objective value if we allow 1 extra tCO~2~? Since the goal of this problem is to minimize cost, an improvement involves a reduction in the objective function, so the shadow price is negative, even though the \"value\" of relaxing the constraint is positive.\n\nThus, every tCO~2~ we allow will be worth \\$183, so allowing an extra 1,000 tCO~2~ will be worth \\$183000.\n\n\n::: {.cell .markdown}\n## References\n\nList any external references consulted, including classmates.\n:::\n\n---\njupyter:\n  kernelspec:\n    display_name: Julia\n    name: julia\n    language: julia\n  kernel_info:\n    name: julia\n  language_info:\n    name: julia\n    version: 1.11.5\n    codemirror_mode: julia\n---\n",
    "supporting": [
      "hw04_files/figure-ipynb"
    ],
    "filters": []
  }
}