---
title: "Quiz Policies"
anchor-sections: true
format: 
    html: default
---

This page includes some information on the exams for BEE 4750/5750, including policies and logistics. 


## Quiz Logistics

This class will have several quizzes (likely 5-6) at the beginning of the given class session. Each quiz will be approximately 4-6 questions, including sub-questions. You will be given 25 minutes to complete each quiz **from the start of the class session**^[We will make arrangements if you have an extended-time SDS accomodation.]. All quiz dates and the scope of the covered material will be announced ahead of time.

Quizzes will be hand-written and then will be scanned into Gradescope (by course staff) for grading and feedback; the physical copy of your exam will not be returned.

No calculators or other electronic devices will be allowed without an SDS accomodation. All calculations can either be completed by hand or it is not necessary that you do the calculations at all (e.g., you may be asked to set up a model, but not solve it).

### Quiz Questions

Due to the short The emphasis is on concepts; there will be no major, in-depth calculations that you will need to complete, and no programming. You will be potentially be asked to set up or interpret conceptual systems models, derive mathematical versions of models, apply or explain concepts from class, and interpret outputs. 

While we will not hand out sample quizzes, quiz problems will resemble simpler homework problems. The goal is to assess your ability to understand concepts, set up problems, determine appropriateness of methods, and interpret the output, rather than on doing computations. We cannot, and do not, expect you to solve problems with full homework-level difficulty in the restricted quiz setting.

In general, the same [homework grading rubric](../policies/rubric.qmd) applies to quiz problems, as appropriate (*.e.g.* nothing about code). The deadly sins will still be penalized, and your solutions should be clear with transparent and well-communicated reasoning.

### Academic Integrity

The quizzes are closed-book and closed-note, and closed everything else. **No medically unnecessary electronic devices are allowed to be used during the exam**, including headphones and smart watches. 


## Accomodations and Conflicts

### SDS Accomodations

Please make sure that any quiz-related accomodations have been provided to the course staff ahead of the first quiz. Extended-time accomodations will be handled by finding a time where you can take the quiz with the appropriate amount of time.

### Conflict and Makeup Quizzes

If you have an academic conflict or a university-approved reason why you cannot take the exam in class, reach out to Prof. Srikrishnan as soon as possible to schedule a makeup.

In **extreme** circumstances, such as long-term illnesses or injuries, that prevent taking both a makeup quiz, we may forgive the quiz and compute your grade without it. This will increase the weight given to other quizzes.